In [29]:
!pip install black
!pip install "black[jupyter]"

Requirement already satisfied: black in /usr/local/lib/python3.12/dist-packages (26.3.1)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black) (8.3.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from black) (1.1.0)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.12/dist-packages (from black) (26.0)
Requirement already satisfied: pathspec>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from black) (1.0.4)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black) (4.9.4)
Requirement already satisfied: pytokens~=0.4.0 in /usr/local/lib/python3.12/dist-packages (from black) (0.4.1)
Requirement already satisfied: black[jupyter] in /usr/local/lib/python3.12/dist-packages (26.3.1)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (8.3.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (1.1.0)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (26.0)
Requirement already satisfied: pathspec>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (1.0.4)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (4.9.4)
Requirement already satisfied: pytokens~=0.4.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (0.4.1)
Requirement already satisfied: ipython>=7.8.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (7.34.0)
Requirement already satisfied: tokenize-rt>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (6.2.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.8.0->black[jupyter]) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=7.8.0->black[jupyter]) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.8.0->black[jupyter]) (0.6.0)

In [30]:
!black "hirehi_parsing.ipynb"

reformatted hirehi_parsing.ipynb

All done! ✨ 🍰 ✨
1 file reformatted.

In [1]:
import requests

In [2]:
url = "https://hirehi.ru/api/search/jobs?limit=50"
page = requests.get(url)

In [3]:
page

In [4]:
print(page.json())

{'filter_counts': {'country': {}, 'direct_contact': 4669, 'english': 2451, 'format': {'гибрид': 1692, 'офис': 1497, 'удалённо': 4571, 'удалённо по РФ': 994}, 'hirehi': 98, 'level': {'head': 63, 'intern': 129, 'junior': 468, 'lead': 768, 'middle': 4235, 'senior': 3089, 'не указан': 1}, 'region': {}, 'salary': {'151–250k': 2886, '250k+': 4073, '81–150k': 990, 'до 80k': 781}}, 'has_more': True, 'initial_filter_counts': {'country': {}, 'direct_contact': 4669, 'english': 2451, 'format': {'гибрид': 1692, 'офис': 1497, 'удалённо': 4571, 'удалённо по РФ': 994}, 'hirehi': 98, 'level': {'head': 63, 'intern': 129, 'junior': 468, 'lead': 768, 'middle': 4235, 'senior': 3089, 'не указан': 1}, 'region': {}, 'salary': {'151–250k': 2886, '250k+': 4073, '81–150k': 990, 'до 80k': 781}}, 'jobs': [{'category': 'qa', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:43:31Z', 'format': 'удалённо по РФ', 'id': 36700, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': 'от 240 000 ₽', 'salary_display': 'от 240 000 ₽', 'title': 'quality assurance (manual)'}, {'category': 'development', 'company': 'Экосистема тенниса', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRUVGMkZGIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRTBFN0ZGIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM2ODZGODciPtCtPC90ZXh0PjwvZz48L3N2Zz4=', 'created_at': '2026-04-08T13:43:04Z', 'format': 'удалённо', 'id': 36699, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': 'от 350 000 ₽', 'salary_display': 'от 350 000 ₽', 'title': 'iOS разработчик'}, {'category': 'devops', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:33:31Z', 'format': 'удалённо', 'id': 36697, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 372 000 ₽', 'salary_display': '~ 372 000 ₽', 'title': 'platform engineer'}, {'category': 'marketing', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:24:49Z', 'format': 'удалённо', 'id': 36696, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 223 000 ₽', 'salary_display': '~ 223 000 ₽', 'title': 'growth marketing manager'}, {'category': 'analytics', 'company': 'ВТБ', 'company_icon': '/static/uploads/_20250322231759.svg', 'created_at': '2026-04-08T13:24:22Z', 'format': 'гибрид Москва', 'id': 36695, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 210 000 ₽', 'salary_display': '~ 210 000 ₽', 'title': 'Бизнес аналитик'}, {'category': 'devops', 'company': 'Сбер', 'company_icon': '/static/uploads/_20260120124330.webp', 'created_at': '2026-04-08T13:23:33Z', 'format': 'гибрид Москва', 'id': 36694, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 345 000 ₽', 'salary_display': '~ 345 000 ₽', 'title': 'DevOps инженер'}, {'category': 'development', 'company': 'Сбер', 'company_icon': '/static/uploads/_20260120124330.webp', 'created_at': '2026-04-08T13:23:04Z', 'format': 'гибрид Н.Новгород', 'id': 36693, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': 'от 90 000 ₽', 'salary_display': 'от 90 000 ₽', 'title': 'Python Developer'}, {'category': 'development', 'company': 'Level 26 Games', 'company_icon': '/static/uploads/Level_26_Games_20251210073112.webp', 'created_at': '2026-04-08T13:21:40Z', 'format': 'удалённо', 'id': 36692, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': 'от 320 000 ₽', 'salary_display': 'от 320 000 ₽', 'title': 'c++ developer'}, {'category': 'analytics', 'company': 'Магнит', 'company_icon': '/static/uploads/_20250322231720.svg', 'created_at': '2026-04-08T13:21:20Z', 'format': 'гибрид Москва', 'id': 36691, 'is_from_recruiter': False, 'is_premium': False, 'level': 'intern', 'salary': '~ 65 000 ₽', 'salary_display': '~ 65 000 ₽', 'title': 'Аналитик данных'}, {'category': 'analytics', 'company': 'МТС', 'company_icon': '/static/uploads/_20250322230810.svg', 'created_at': '2026-04-08T13:20:41Z', 'format': 'удалённо по РФ', 'id': 36690, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 282 000 ₽', 'salary_display': '~ 282 000 ₽', 'title': 'Системный аналитик'}, {'category': 'management', 'company': 'Cloud.ru', 'company_icon': '/static/uploads/Cloud.ru_20250427102326.webp', 'created_at': '2026-04-08T13:20:10Z', 'format': 'гибрид Москва', 'id': 36689, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 386 000 ₽', 'salary_display': '~ 386 000 ₽', 'title': 'Менеджер продукта'}, {'category': 'marketing', 'company': 'Dicebet', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGMEY1Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZEOUU2Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4NzYxNkUiPkQ8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:17:54Z', 'format': 'офис', 'id': 36688, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '80 000 ₽', 'salary_display': '80 000 ₽', 'title': 'media buyer'}, {'category': 'devops', 'company': 'Касперский', 'company_icon': '/static/uploads/_20250324120655.webp', 'created_at': '2026-04-08T13:14:00Z', 'format': 'удалённо по РФ', 'id': 36687, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': 'зп не указана', 'salary_display': 'зп не указана', 'title': 'DevOps Engineer'}, {'category': 'analytics', 'company': 'Aston', 'company_icon': '/static/uploads/Aston_20250627094741.webp', 'created_at': '2026-04-08T13:13:31Z', 'format': 'удалённо', 'id': 36686, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 210 000 ₽', 'salary_display': '~ 210 000 ₽', 'title': 'Аналитик данных'}, {'category': 'management', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:12:37Z', 'format': 'удалённо', 'id': 36685, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 371 000 ₽', 'salary_display': '~ 371 000 ₽', 'title': 'продакт-менеджер'}, {'category': 'development', 'company': 'Сбер', 'company_icon': '/static/uploads/_20260120124330.webp', 'created_at': '2026-04-08T13:11:49Z', 'format': 'офис Москва', 'id': 36684, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 318 000 ₽', 'salary_display': '~ 318 000 ₽', 'title': 'Python Developer'}, {'category': 'qa', 'company': 'Альфа-банк', 'company_icon': '/static/uploads/-_20250401094044.svg', 'created_at': '2026-04-08T13:11:26Z', 'format': 'удалённо по РФ', 'id': 36683, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': 'от 180 000 ₽', 'salary_display': 'от 180 000 ₽', 'title': 'qa engineer (auto)'}, {'category': 'analytics', 'company': 'IT People', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPkk8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:10:57Z', 'format': 'удалённо по РФ', 'id': 36682, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 204 000 ₽', 'salary_display': '~ 204 000 ₽', 'title': 'аналитик данных'}, {'category': 'marketing', 'company': 'Elbax', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRjFGNUY5Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRTJFOEYwIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM2QTcwNzgiPkU8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:10:34Z', 'format': 'удалённо', 'id': 36681, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 220 000 ₽', 'salary_display': '~ 220 000 ₽', 'title': 'seo specialist'}, {'category': 'marketing', 'company': 'ChatPlace', 'company_icon': '/static/uploads/ChatPlace_20251110074948.webp', 'created_at': '2026-04-08T13:10:09Z', 'format': 'удалённо', 'id': 36680, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': 'от 160 000 ₽', 'salary_display': 'от 160 000 ₽', 'title': 'influencer manager'}, {'category': 'development', 'company': 'Viviane Talents', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRjJFQ0ZGIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRTNEOEZGIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM2QjYwODciPlY8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:09:42Z', 'format': 'удалённо', 'id': 36679, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': 'от 240 000 ₽', 'salary_display': 'от 240 000 ₽', 'title': 'data engineer'}, {'category': 'marketing', 'company': 'HydroForma', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRjFGNUY5Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRTJFOEYwIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM2QTcwNzgiPkg8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T13:08:59Z', 'format': 'удалённо', 'id': 36678, 'is_from_recruiter': False, 'is_premium': False, 'level': 'junior', 'salary': '40 000 ₽', 'salary_display': '40 000 ₽', 'title': 'smm-менеджер'}, {'category': 'development', 'company': 'Сбер', 'company_icon': '/static/uploads/_20260120124330.webp', 'created_at': '2026-04-08T12:54:00Z', 'format': 'гибрид Москва', 'id': 36677, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 215 000 ₽', 'salary_display': '~ 215 000 ₽', 'title': 'Vue Developer'}, {'category': 'management', 'company': 'Ozon', 'company_icon': '/static/uploads/Ozon_20250322230928.svg', 'created_at': '2026-04-08T12:53:33Z', 'format': 'гибрид Москва', 'id': 36676, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 395 000 ₽', 'salary_display': '~ 395 000 ₽', 'title': 'Product Owner'}, {'category': 'analytics', 'company': 'ВКонтакте', 'company_icon': '/static/uploads/_20250322224658.svg', 'created_at': '2026-04-08T12:53:17Z', 'format': 'гибрид Москва', 'id': 36675, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 320 000 ₽', 'salary_display': '~ 320 000 ₽', 'title': 'Продуктовый аналитик'}, {'category': 'development', 'company': 'Яндекс Реклама', 'company_icon': '/static/uploads/_20250820140100.webp', 'created_at': '2026-04-08T12:52:29Z', 'format': 'гибрид Москва', 'id': 36674, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 411 000 ₽', 'salary_display': '~ 411 000 ₽', 'title': 'C++ разработчик'}, {'category': 'management', 'company': 'Ozon', 'company_icon': '/static/uploads/Ozon_20250322230928.svg', 'created_at': '2026-04-08T12:51:59Z', 'format': 'гибрид Москва', 'id': 36673, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 409 000 ₽', 'salary_display': '~ 409 000 ₽', 'title': 'руководитель продукта'}, {'category': 'management', 'company': 'Ozon', 'company_icon': '/static/uploads/Ozon_20250322230928.svg', 'created_at': '2026-04-08T12:51:34Z', 'format': 'офис Москва', 'id': 36672, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 227 000 ₽', 'salary_display': '~ 227 000 ₽', 'title': 'Менеджер продукта'}, {'category': 'marketing', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0

In [5]:
a = [page.json()["limit"], page.json()["page"], page.json()["total_count"]]
a

[50, 1, 8754]

In [6]:
import math

pageamount = math.ceil(a[2] / a[0])
pageamount

176

In [7]:
data = page.json()
jobs = data["jobs"]
first = jobs[0]
print(first.keys())

dict_keys(['category', 'company', 'company_icon', 'created_at', 'format', 'id', 'is_from_recruiter', 'is_premium', 'level', 'salary', 'salary_display', 'title'])

In [8]:
def get_page(p):
    url = f"https://hirehi.ru/api/search/jobs?page={p}&limit=50"
    response = requests.get(url)
    jobs = response.json()["jobs"]
    clean_data = []
    for i in jobs:
        cleanvac = {
            "id": i.get("id"),
            "title": i.get("title"),
            "category": i.get("category"),
            "company": i.get("company"),
            "format": i.get("format"),
            "level": i.get("level"),
            "salary": i.get("salary"),
        }
        clean_data.append(cleanvac)
    return clean_data

In [9]:
from tqdm.notebook import tqdm

In [10]:
infa = []
for p in tqdm(range(1, pageamount + 1)):
    try:
        infa.extend(get_page(p))
        sleep(3)
    except:
        print(p)

  0%|          | 0/176 [00:00<?, ?it/s]

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176

In [12]:
import pandas as pd

df = pd.DataFrame(infa)
print(df.shape)
df.head(10)

(8754, 7)

,id,title,category,company,format,level,salary
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽
5,36694,DevOps инженер,devops,Сбер,гибрид Москва,senior,~ 345 000 ₽
6,36693,Python Developer,development,Сбер,гибрид Н.Новгород,middle,от 90 000 ₽
7,36692,c++ developer,development,Level 26 Games,удалённо,senior,от 320 000 ₽
8,36691,Аналитик данных,analytics,Магнит,гибрид Москва,intern,~ 65 000 ₽
9,36690,Системный аналитик,analytics,МТС,удалённо по РФ,senior,~ 282 000 ₽

Далее соберем ссылки:</br>
.NET Developer</br>
https://hirehi.ru/development/net-developer-36177</br>
графический дизайнер</br>
https://hirehi.ru/design/graficheskii-dizainer-36174</br>
Сылки выглядят таким образом , то есть https://hirehi.ru/{category}/{title}-{id}
</br>Все title приведены к нижнему регистру, текст на русском транслитерирован, все символы, кроме букв заменены на "-", крайние дефисы удалены, для этого можно использовать модуль **transliterate**.
Создадим дополнительные колонки для транслитерации русского текста в колонках **title** и **category**.

Если текст состоит из слов только на английском, то выводится none, значит текст, который написан на английском оставляем как есть. </br> Такжде слэши удаляются и не заменяются на дефисы, как должно быть с карточкой UX/UI дизайнер https://hirehi.ru/design/ux-ui-dizainer-36159

In [13]:
df["title_trans"] = df["title"]
df["id_trans"] = df["id"]
df.head(10)

,id,title,category,company,format,level,salary,title_trans,id_trans
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,quality assurance (manual),36700
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,iOS разработчик,36699
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,platform engineer,36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,growth marketing manager,36696
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,Бизнес аналитик,36695
5,36694,DevOps инженер,devops,Сбер,гибрид Москва,senior,~ 345 000 ₽,DevOps инженер,36694
6,36693,Python Developer,development,Сбер,гибрид Н.Новгород,middle,от 90 000 ₽,Python Developer,36693
7,36692,c++ developer,development,Level 26 Games,удалённо,senior,от 320 000 ₽,c++ developer,36692
8,36691,Аналитик данных,analytics,Магнит,гибрид Москва,intern,~ 65 000 ₽,Аналитик данных,36691
9,36690,Системный аналитик,analytics,МТС,удалённо по РФ,senior,~ 282 000 ₽,Системный аналитик,36690

In [14]:
df["title_trans"] = df["title_trans"].astype(str).str.lower()
df["id_trans"] = df["id_trans"].astype(str)
df.head(10)

,id,title,category,company,format,level,salary,title_trans,id_trans
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,quality assurance (manual),36700
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,ios разработчик,36699
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,platform engineer,36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,growth marketing manager,36696
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,бизнес аналитик,36695
5,36694,DevOps инженер,devops,Сбер,гибрид Москва,senior,~ 345 000 ₽,devops инженер,36694
6,36693,Python Developer,development,Сбер,гибрид Н.Новгород,middle,от 90 000 ₽,python developer,36693
7,36692,c++ developer,development,Level 26 Games,удалённо,senior,от 320 000 ₽,c++ developer,36692
8,36691,Аналитик данных,analytics,Магнит,гибрид Москва,intern,~ 65 000 ₽,аналитик данных,36691
9,36690,Системный аналитик,analytics,МТС,удалённо по РФ,senior,~ 282 000 ₽,системный аналитик,36690

In [15]:
df["title_trans"] = (
    df["title_trans"]
    .str.replace(r"[^\w]", "-", regex=True)
    .str.replace(r"_", "-", regex=True)
)
df

,id,title,category,company,format,level,salary,title_trans,id_trans
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,quality-assurance--manual-,36700
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,ios-разработчик,36699
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,platform-engineer,36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,growth-marketing-manager,36696
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,бизнес-аналитик,36695
...,...,...,...,...,...,...,...,...,...
8749,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,24856
8750,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,разработчик-php,24838
8751,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,проектный-менеджер-it,24836
8752,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,системный-аналитик,24787
8753,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,24786

нужно удалить повторяющиеся дефисы и дефисы в начале/конце

In [16]:
df["title_trans"] = df["title_trans"].str.replace(r"-+", "-", regex=True)
df

,id,title,category,company,format,level,salary,title_trans,id_trans
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,quality-assurance-manual-,36700
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,ios-разработчик,36699
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,platform-engineer,36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,growth-marketing-manager,36696
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,бизнес-аналитик,36695
...,...,...,...,...,...,...,...,...,...
8749,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,24856
8750,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,разработчик-php,24838
8751,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,проектный-менеджер-it,24836
8752,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,системный-аналитик,24787
8753,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,24786

In [17]:
df["title_trans"] = df["title_trans"].str.strip("-")
df

,id,title,category,company,format,level,salary,title_trans,id_trans
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,quality-assurance-manual,36700
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,ios-разработчик,36699
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,platform-engineer,36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,growth-marketing-manager,36696
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,бизнес-аналитик,36695
...,...,...,...,...,...,...,...,...,...
8749,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,24856
8750,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,разработчик-php,24838
8751,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,проектный-менеджер-it,24836
8752,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,системный-аналитик,24787
8753,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,24786

напишем функцию, которая будет транслитерировать русский текст, а английский оставлять как есть

In [18]:
def makelink1(i):
    letters = {
        "а": "a",
        "б": "b",
        "в": "v",
        "г": "g",
        "д": "d",
        "е": "e",
        "ё": "e",
        "ж": "zh",
        "з": "z",
        "и": "i",
        "й": "i",
        "к": "k",
        "л": "l",
        "м": "m",
        "н": "n",
        "о": "o",
        "п": "p",
        "р": "r",
        "с": "s",
        "т": "t",
        "у": "u",
        "ф": "f",
        "х": "h",
        "ц": "ts",
        "ч": "ch",
        "ш": "sh",
        "щ": "sch",
        "ъ": "",
        "ы": "y",
        "ь": "",
        "э": "e",
        "ю": "yu",
        "я": "ya",
    }
    ready = ""
    for s in i:
        if s in letters:
            ready += letters[s]
        else:
            ready += s
    return ready

In [19]:
df["title_trans"] = df["title_trans"].apply(makelink1)
df

,id,title,category,company,format,level,salary,title_trans,id_trans
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,quality-assurance-manual,36700
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,ios-razrabotchik,36699
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,platform-engineer,36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,growth-marketing-manager,36696
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,biznes-analitik,36695
...,...,...,...,...,...,...,...,...,...
8749,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,24856
8750,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,razrabotchik-php,24838
8751,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,proektnyi-menedzher-it,24836
8752,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,sistemnyi-analitik,24787
8753,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,24786

Теперь соберем ссылку в том виде, в котором она должна быть <br>
https://hirehi.ru/{category}/{title}-{id}

In [23]:
df["link"] = (
    "https://hirehi.ru/"
    + df["category"]
    + "/"
    + df["title_trans"]
    + "-"
    + df["id_trans"]
)
df

,id,title,category,company,format,level,salary,title_trans,id_trans,link
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,quality-assurance-manual,36700,https://hirehi.ru/qa/quality-assurance-manual-...
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,ios-razrabotchik,36699,https://hirehi.ru/development/ios-razrabotchik...
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,platform-engineer,36697,https://hirehi.ru/devops/platform-engineer-36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,growth-marketing-manager,36696,https://hirehi.ru/marketing/growth-marketing-m...
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,biznes-analitik,36695,https://hirehi.ru/analytics/biznes-analitik-36695
...,...,...,...,...,...,...,...,...,...,...
8749,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,24856,https://hirehi.ru/development/ml-engineer-24856
8750,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,razrabotchik-php,24838,https://hirehi.ru/development/razrabotchik-php...
8751,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,proektnyi-menedzher-it,24836,https://hirehi.ru/management/proektnyi-menedzh...
8752,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,sistemnyi-analitik,24787,https://hirehi.ru/analytics/sistemnyi-analitik...
8753,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,24786,https://hirehi.ru/devops/devops-engineer-24786

мы получили ссылки, но можно заметить такую проблему, что transliterate заменяет буквы не так "по-русски", в наших ссылках пишется **ux-ui-dizajner**, когда в оригинальной ссылке используется **ux-ui-dizainer**
значит библиотека не сможет "правильно" транслитерировать наш текст. Поэтому напишем словарь, с помощью которого можно будет просто заменять русскую букву на английскую, без дополнительных правил библиотеки, когда две гласные стоят рядом и происходит удвоение.

In [24]:
df.drop(columns=["title_trans", "id_trans"], inplace=True)
df

,id,title,category,company,format,level,salary,link
0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,https://hirehi.ru/qa/quality-assurance-manual-...
1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,https://hirehi.ru/development/ios-razrabotchik...
2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,https://hirehi.ru/devops/platform-engineer-36697
3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,https://hirehi.ru/marketing/growth-marketing-m...
4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,https://hirehi.ru/analytics/biznes-analitik-36695
...,...,...,...,...,...,...,...,...
8749,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,https://hirehi.ru/development/ml-engineer-24856
8750,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,https://hirehi.ru/development/razrabotchik-php...
8751,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,https://hirehi.ru/management/proektnyi-menedzh...
8752,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,https://hirehi.ru/analytics/sistemnyi-analitik...
8753,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,https://hirehi.ru/devops/devops-engineer-24786

In [25]:
df.to_csv("hirehi_parsing.csv", index=False)