In [1]:
!pip install black
!pip install "black[jupyter]"

Collecting black
  Downloading black-26.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.9/91.9 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black) (8.3.1)
Collecting mypy-extensions>=0.4.3 (from black)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.12/dist-packages (from black) (26.0)
Collecting pathspec>=1.0.0 (from black)
  Downloading pathspec-1.0.4-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black) (4.9.4)
Collecting pytokens~=0.4.0 (from black)
  Downloading pytokens-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading black-26.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.9 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pathspec-1.0.4-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 2.1 MB/s eta 0:00:00
Downloading pytokens-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (269 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.8/269.8 kB 8.1 MB/s eta 0:00:00
Installing collected packages: pytokens, pathspec, mypy-extensions, black
Successfully installed black-26.3.1 mypy-extensions-1.1.0 pathspec-1.0.4 pytokens-0.4.1
Requirement already satisfied: black[jupyter] in /usr/local/lib/python3.12/dist-packages (26.3.1)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (8.3.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (1.1.0)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (26.0)
Requirement already satisfied: pathspec>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (1.0.4)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (4.9.4)
Requirement already satisfied: pytokens~=0.4.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (0.4.1)
Requirement already satisfied: ipython>=7.8.0 in /usr/local/lib/python3.12/dist-packages (from black[jupyter]) (7.34.0)
Collecting tokenize-rt>=3.2.0 (from black[jupyter])
  Downloading tokenize_rt-6.2.0-py2.py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.8.0->black[jupyter])
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.8.0->black[jupyter]) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.8.0->black[jupyter]) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=7.8.0->black[jupyter]) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.8.0->black[jupyter]) (0.6.0)
Downloading tokenize_rt-6.2.0-py2.py3-none-any.whl (6.0 kB)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 28.3 MB/s eta 0:00:00
Installing collected packages: tokenize-rt, jedi
Successfully installed jedi-0.19.2 tokenize-rt-6.2.0

In [2]:
!black "requests2.ipynb"

Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.

Error: Invalid value for 'SRC ...': Path 'requests2.ipynb' does not exist.

In [3]:
import requests

In [4]:
url = "https://hirehi.ru/api/search/jobs?limit=50"
page = requests.get(url)

In [5]:
page

In [6]:
print(page.json())

{'filter_counts': {'country': {}, 'direct_contact': 4658, 'english': 2444, 'format': {'гибрид': 1687, 'офис': 1495, 'удалённо': 4561, 'удалённо по РФ': 989}, 'hirehi': 98, 'level': {'head': 63, 'intern': 128, 'junior': 467, 'lead': 768, 'middle': 4227, 'senior': 3077, 'не указан': 1}, 'region': {}, 'salary': {'151–250k': 2877, '250k+': 4065, '81–150k': 989, 'до 80k': 777}}, 'has_more': True, 'initial_filter_counts': {'country': {}, 'direct_contact': 4658, 'english': 2444, 'format': {'гибрид': 1687, 'офис': 1495, 'удалённо': 4561, 'удалённо по РФ': 989}, 'hirehi': 98, 'level': {'head': 63, 'intern': 128, 'junior': 467, 'lead': 768, 'middle': 4227, 'senior': 3077, 'не указан': 1}, 'region': {}, 'salary': {'151–250k': 2877, '250k+': 4065, '81–150k': 989, 'до 80k': 777}}, 'jobs': [{'category': 'development', 'company': 'Сбер', 'company_icon': '/static/uploads/_20260120124330.webp', 'created_at': '2026-04-08T12:54:00Z', 'format': 'гибрид Москва', 'id': 36677, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 215 000 ₽', 'salary_display': '~ 215 000 ₽', 'title': 'Vue Developer'}, {'category': 'management', 'company': 'Ozon', 'company_icon': '/static/uploads/Ozon_20250322230928.svg', 'created_at': '2026-04-08T12:53:33Z', 'format': 'гибрид Москва', 'id': 36676, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 395 000 ₽', 'salary_display': '~ 395 000 ₽', 'title': 'Product Owner'}, {'category': 'analytics', 'company': 'ВКонтакте', 'company_icon': '/static/uploads/_20250322224658.svg', 'created_at': '2026-04-08T12:53:17Z', 'format': 'гибрид Москва', 'id': 36675, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 320 000 ₽', 'salary_display': '~ 320 000 ₽', 'title': 'Продуктовый аналитик'}, {'category': 'development', 'company': 'Яндекс Реклама', 'company_icon': '/static/uploads/_20250820140100.webp', 'created_at': '2026-04-08T12:52:29Z', 'format': 'гибрид Москва', 'id': 36674, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 411 000 ₽', 'salary_display': '~ 411 000 ₽', 'title': 'C++ разработчик'}, {'category': 'management', 'company': 'Ozon', 'company_icon': '/static/uploads/Ozon_20250322230928.svg', 'created_at': '2026-04-08T12:51:59Z', 'format': 'гибрид Москва', 'id': 36673, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 409 000 ₽', 'salary_display': '~ 409 000 ₽', 'title': 'руководитель продукта'}, {'category': 'management', 'company': 'Ozon', 'company_icon': '/static/uploads/Ozon_20250322230928.svg', 'created_at': '2026-04-08T12:51:34Z', 'format': 'офис Москва', 'id': 36672, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 227 000 ₽', 'salary_display': '~ 227 000 ₽', 'title': 'Менеджер продукта'}, {'category': 'marketing', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:51:14Z', 'format': 'удалённо', 'id': 36671, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '240 000 ₽', 'salary_display': '240 000 ₽', 'title': 'seo specialist'}, {'category': 'development', 'company': 'Nexora', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRThGQkY3Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjQ0ZGNUVDIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM1NzdENzQiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:50:03Z', 'format': 'удалённо', 'id': 36670, 'is_from_recruiter': False, 'is_premium': False, 'level': 'junior', 'salary': '~ 68 000 ₽', 'salary_display': '~ 68 000 ₽', 'title': 'fullstack developer'}, {'category': 'development', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:49:32Z', 'format': 'удалённо', 'id': 36669, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '80 000 ₽', 'salary_display': '80 000 ₽', 'title': 'react native developer'}, {'category': 'development', 'company': 'Aston', 'company_icon': '/static/uploads/Aston_20250627094741.webp', 'created_at': '2026-04-08T12:49:03Z', 'format': 'удалённо', 'id': 36668, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 325 000 ₽', 'salary_display': '~ 325 000 ₽', 'title': 'Java Developer'}, {'category': 'development', 'company': '2ГИС', 'company_icon': '/static/uploads/2_20250322230558.svg', 'created_at': '2026-04-08T12:48:39Z', 'format': 'удалённо', 'id': 36667, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 265 000 ₽', 'salary_display': '~ 265 000 ₽', 'title': 'C# Developer'}, {'category': 'development', 'company': 'Capital Network', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRUNGREYzIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRDFGQUU1Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM1OTgyNkQiPkM8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:48:13Z', 'format': 'офис Астана', 'id': 36666, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': 'от 192 000 ₽', 'salary_display': 'от 192 000 ₽', 'title': 'fullstack developer'}, {'category': 'development', 'company': 'Космос Про Медиа', 'company_icon': '/static/uploads/_20251008070307.webp', 'created_at': '2026-04-08T12:47:49Z', 'format': 'удалённо', 'id': 36665, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': 'от 240 000 ₽', 'salary_display': 'от 240 000 ₽', 'title': 'frontend developer'}, {'category': 'development', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:47:21Z', 'format': 'удалённо', 'id': 36664, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 393 000 ₽', 'salary_display': '~ 393 000 ₽', 'title': 'android developer'}, {'category': 'development', 'company': 'IT People', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPkk8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:46:44Z', 'format': 'удалённо по РФ', 'id': 36663, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 226 000 ₽', 'salary_display': '~ 226 000 ₽', 'title': 'ios developer'}, {'category': 'development', 'company': 'Яндекс Директ', 'company_icon': '/static/uploads/_20250407060428.webp', 'created_at': '2026-04-08T12:46:22Z', 'format': 'гибрид Москва', 'id': 36662, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 381 000 ₽', 'salary_display': '~ 381 000 ₽', 'title': 'Ml engineer'}, {'category': 'development', 'company': 'Суточно.ру', 'company_icon': '/static/uploads/_20250908071450.webp', 'created_at': '2026-04-08T12:45:42Z', 'format': 'удалённо', 'id': 36661, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 387 000 ₽', 'salary_display': '~ 387 000 ₽', 'title': 'Golang разработчик'}, {'category': 'design', 'company': 'VolnitsaGames', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRThGQkY3Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjQ0ZGNUVDIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM1NzdENzQiPlY8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:44:56Z', 'format': 'удалённо', 'id': 36660, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 172 000 ₽', 'salary_display': '~ 172 000 ₽', 'title': 'ux/ui-дизайнер'}, {'category': 'qa', 'company': 'Сбер', 'company_icon': '/static/uploads/_20260120124330.webp', 'created_at': '2026-04-08T12:44:35Z', 'format': 'гибрид Питер', 'id': 36659, 'is_from_recruiter': False, 'is_premium': False, 'level': 'junior', 'salary': '~ 82 000 ₽', 'salary_display': '~ 82 000 ₽', 'title': 'automation qa'}, {'category': 'devops', 'company': 'Muse Group', 'company_icon': '/static/uploads/Muse_Group_20250819071547.webp', 'created_at': '2026-04-08T12:43:28Z', 'format': 'удалённо', 'id': 36658, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 410 000 ₽', 'salary_display': '~ 410 000 ₽', 'title': 'DevOps Engineer'}, {'category': 'analytics', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:42:38Z', 'format': 'офис Минск', 'id': 36657, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 168 000 ₽', 'salary_display': '~ 168 000 ₽', 'title': 'business analyst'}, {'category': 'development', 'company': 'Nexora', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRThGQkY3Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjQ0ZGNUVDIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM1NzdENzQiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:42:03Z', 'format': 'удалённо', 'id': 36656, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 168 000 ₽', 'salary_display': '~ 168 000 ₽', 'title': 'fullstack developer'}, {'category': 'marketing', 'company': 'Blackcat', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRUVGMkZGIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRTBFN0ZGIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM2ODZGODciPkI8L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:41:19Z', 'format': 'удалённо', 'id': 36655, 'is_from_recruiter': False, 'is_premium': False, 'level': 'senior', 'salary': '~ 231 000 ₽', 'salary_display': '~ 231 000 ₽', 'title': 'content manager'}, {'category': 'devops', 'company': 'ЮМани', 'company_icon': '/static/uploads/_20251123172044.webp', 'created_at': '2026-04-08T12:40:44Z', 'format': 'гибрид', 'id': 36654, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 231 000 ₽', 'salary_display': '~ 231 000 ₽', 'title': 'infrastructure engineer'}, {'category': 'marketing', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJJbnRlciwgc3lzdGVtLXVpLCAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICdTZWdvZSBVSScsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTIiIGZvbnQtd2VpZ2h0PSI2MDAiIGZpbGw9IiM4Nzc5NDEiPk48L3RleHQ+PC9nPjwvc3ZnPg==', 'created_at': '2026-04-08T12:40:17Z', 'format': 'удалённо', 'id': 36653, 'is_from_recruiter': False, 'is_premium': False, 'level': 'lead', 'salary': '~ 200 000 ₽', 'salary_display': '~ 200 000 ₽', 'title': 'head of affiliate'}, {'category': 'devops', 'company': 'Т1', 'company_icon': '/static/uploads/1_20250416072317.webp', 'created_at': '2026-04-08T12:39:41Z', 'format': 'удалённо', 'id': 36652, 'is_from_recruiter': False, 'is_premium': False, 'level': 'middle', 'salary': '~ 265 000 ₽', 'salary_display': '~ 265 000 ₽', 'title': 'DevOps Engineer'}, {'category': 'design', 'company': 'NDA', 'company_icon': 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PGcgaWQ9ImhpcmVoaS1jb21wYW55LXBsYWNlaG9sZGVyIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImhpcmVoaUNvbXBhbnlQbGFjZWhvbGRlckdyYWRpZW50IiB4MT0iMTIiIHkxPSIxLjUiIHgyPSIxMiIgeTI9IjIyLjUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRkZGQkU2Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRkZGMUI4Ii8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiIGZpbGw9InVybCgjaGlyZWhpQ29tcGFueVBsYWNlaG9sZGVyR3JhZGllbnQpIi8+PHRleHQgeD0iMTIiIHk9IjEzLjEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50L

In [7]:
a = [page.json()["limit"], page.json()["page"], page.json()["total_count"]]
a

[50, 1, 8732]

In [8]:
import math

pageamount = math.ceil(a[2] / a[0])
pageamount

175

In [9]:
data = page.json()
jobs = data["jobs"]
first = jobs[0]
print(first.keys())

dict_keys(['category', 'company', 'company_icon', 'created_at', 'format', 'id', 'is_from_recruiter', 'is_premium', 'level', 'salary', 'salary_display', 'title'])

In [10]:
def get_page(p):
    url = f"https://hirehi.ru/api/search/jobs?page={p}&limit=50"
    response = requests.get(url)
    jobs = response.json()["jobs"]
    clean_data = []
    for i in jobs:
        cleanvac = {
            "id": i.get("id"),
            "title": i.get("title"),
            "category": i.get("category"),
            "company": i.get("company"),
            "format": i.get("format"),
            "level": i.get("level"),
            "salary": i.get("salary"),
        }
        clean_data.append(cleanvac)
    return clean_data

In [11]:
from tqdm.notebook import tqdm

In [12]:
infa = []
for p in tqdm(range(1, pageamount + 1)):
    try:
        infa.extend(get_page(p))
        sleep(3)
    except:
        print(p)

  0%|          | 0/175 [00:00<?, ?it/s]

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175

In [13]:
import pandas as pd

df = pd.DataFrame(infa)
print(df.shape)
df.head(10)

(8732, 7)

,id,title,category,company,format,level,salary
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽
5,36672,Менеджер продукта,management,Ozon,офис Москва,middle,~ 227 000 ₽
6,36671,seo specialist,marketing,NDA,удалённо,senior,240 000 ₽
7,36670,fullstack developer,development,Nexora,удалённо,junior,~ 68 000 ₽
8,36669,react native developer,development,NDA,удалённо,middle,80 000 ₽
9,36668,Java Developer,development,Aston,удалённо,lead,~ 325 000 ₽

Далее соберем ссылки:</br>
.NET Developer</br>
https://hirehi.ru/development/net-developer-36177</br>
графический дизайнер</br>
https://hirehi.ru/design/graficheskii-dizainer-36174</br>
Сылки выглядят таким образом , то есть https://hirehi.ru/{category}/{title}-{id}
</br>Все title приведены к нижнему регистру, текст на русском транслитерирован, все символы, кроме букв заменены на "-", крайние дефисы удалены, для этого можно использовать модуль **transliterate**.
Создадим дополнительные колонки для транслитерации русского текста в колонках **title** и **category**.

Если текст состоит из слов только на английском, то выводится none, значит текст, который написан на английском оставляем как есть. </br> Такжде слэши удаляются и не заменяются на дефисы, как должно быть с карточкой UX/UI дизайнер https://hirehi.ru/design/ux-ui-dizainer-36159

In [16]:
df["title_trans"] = df["title"]
df["category_trans"] = df["category"]
df["id_trans"] = df["id"]
df.head(10)

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,Vue Developer,development,36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,Product Owner,management,36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,Продуктовый аналитик,analytics,36675
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,C++ разработчик,development,36674
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,руководитель продукта,management,36673
5,36672,Менеджер продукта,management,Ozon,офис Москва,middle,~ 227 000 ₽,Менеджер продукта,management,36672
6,36671,seo specialist,marketing,NDA,удалённо,senior,240 000 ₽,seo specialist,marketing,36671
7,36670,fullstack developer,development,Nexora,удалённо,junior,~ 68 000 ₽,fullstack developer,development,36670
8,36669,react native developer,development,NDA,удалённо,middle,80 000 ₽,react native developer,development,36669
9,36668,Java Developer,development,Aston,удалённо,lead,~ 325 000 ₽,Java Developer,development,36668

In [17]:
df["title_trans"] = df["title_trans"].astype(str).str.lower()
df["category_trans"] = df["category_trans"].astype(str).str.lower()
df["id_trans"] = df["id_trans"].astype(str)
df.head(10)

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,vue developer,development,36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,product owner,management,36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,продуктовый аналитик,analytics,36675
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,c++ разработчик,development,36674
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,руководитель продукта,management,36673
5,36672,Менеджер продукта,management,Ozon,офис Москва,middle,~ 227 000 ₽,менеджер продукта,management,36672
6,36671,seo specialist,marketing,NDA,удалённо,senior,240 000 ₽,seo specialist,marketing,36671
7,36670,fullstack developer,development,Nexora,удалённо,junior,~ 68 000 ₽,fullstack developer,development,36670
8,36669,react native developer,development,NDA,удалённо,middle,80 000 ₽,react native developer,development,36669
9,36668,Java Developer,development,Aston,удалённо,lead,~ 325 000 ₽,java developer,development,36668

In [18]:
df["title_trans"] = (
    df["title_trans"]
    .str.replace(r"[^\w]", "-", regex=True)
    .str.replace(r"_", "-", regex=True)
)
df["category_trans"] = (
    df["category_trans"]
    .str.replace(r"[^\w]", "-", regex=True)
    .str.replace(r"_", "-", regex=True)
)
df

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,vue-developer,development,36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,product-owner,management,36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,продуктовый-аналитик,analytics,36675
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,c---разработчик,development,36674
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,руководитель-продукта,management,36673
...,...,...,...,...,...,...,...,...,...,...
8727,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,development,24856
8728,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,разработчик-php,development,24838
8729,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,проектный-менеджер-it,management,24836
8730,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,системный-аналитик,analytics,24787
8731,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,devops,24786

In [19]:
df[df["id"] == 36177]

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans
492,36177,.NET Developer,development,Bell Integrator,гибрид Москва,senior,~ 313 000 ₽,-net-developer,development,36177

нужно удалить повторяющиеся дефисы и дефисы в начале/конце

In [20]:
df["title_trans"] = df["title_trans"].str.replace(r"-+", "-", regex=True)
df["category_trans"] = df["category_trans"].str.replace(r"-+", "-", regex=True)
df

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,vue-developer,development,36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,product-owner,management,36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,продуктовый-аналитик,analytics,36675
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,c-разработчик,development,36674
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,руководитель-продукта,management,36673
...,...,...,...,...,...,...,...,...,...,...
8727,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,development,24856
8728,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,разработчик-php,development,24838
8729,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,проектный-менеджер-it,management,24836
8730,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,системный-аналитик,analytics,24787
8731,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,devops,24786

In [21]:
df["title_trans"] = df["title_trans"].str.strip("-")
df["category_trans"] = df["category_trans"].str.strip("-")
df

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,vue-developer,development,36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,product-owner,management,36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,продуктовый-аналитик,analytics,36675
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,c-разработчик,development,36674
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,руководитель-продукта,management,36673
...,...,...,...,...,...,...,...,...,...,...
8727,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,development,24856
8728,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,разработчик-php,development,24838
8729,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,проектный-менеджер-it,management,24836
8730,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,системный-аналитик,analytics,24787
8731,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,devops,24786

напишем функцию, которая будет транслитерировать русский текст, а английский оставлять как есть

In [23]:
def makelink1(i):
    letters = {
        "а": "a",
        "б": "b",
        "в": "v",
        "г": "g",
        "д": "d",
        "е": "e",
        "ё": "e",
        "ж": "zh",
        "з": "z",
        "и": "i",
        "й": "i",
        "к": "k",
        "л": "l",
        "м": "m",
        "н": "n",
        "о": "o",
        "п": "p",
        "р": "r",
        "с": "s",
        "т": "t",
        "у": "u",
        "ф": "f",
        "х": "h",
        "ц": "ts",
        "ч": "ch",
        "ш": "sh",
        "щ": "sch",
        "ъ": "",
        "ы": "y",
        "ь": "",
        "э": "e",
        "ю": "yu",
        "я": "ya",
    }
    ready = ""
    for s in i:
        if s in letters:
            ready += letters[s]
        else:
            ready += s
    return ready

In [24]:
df["title_trans"] = df["title_trans"].apply(makelink1)
df["category_trans"] = df["category_trans"].apply(makelink1)
df

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,vue-developer,development,36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,product-owner,management,36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,produktovyi-analitik,analytics,36675
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,c-razrabotchik,development,36674
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,rukovoditel-produkta,management,36673
...,...,...,...,...,...,...,...,...,...,...
8727,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,development,24856
8728,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,razrabotchik-php,development,24838
8729,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,proektnyi-menedzher-it,management,24836
8730,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,sistemnyi-analitik,analytics,24787
8731,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,devops,24786

Теперь соберем ссылку в том виде, в котором она должна быть <br>
https://hirehi.ru/{category}/{title}-{id}

In [25]:
df["link"] = (
    "https://hirehi.ru/"
    + df["category_trans"]
    + "/"
    + df["title_trans"]
    + "-"
    + df["id_trans"]
)
df

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans,link
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,vue-developer,development,36677,https://hirehi.ru/development/vue-developer-36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,product-owner,management,36676,https://hirehi.ru/management/product-owner-36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,produktovyi-analitik,analytics,36675,https://hirehi.ru/analytics/produktovyi-analit...
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,c-razrabotchik,development,36674,https://hirehi.ru/development/c-razrabotchik-3...
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,rukovoditel-produkta,management,36673,https://hirehi.ru/management/rukovoditel-produ...
...,...,...,...,...,...,...,...,...,...,...,...
8727,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,ml-engineer,development,24856,https://hirehi.ru/development/ml-engineer-24856
8728,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,razrabotchik-php,development,24838,https://hirehi.ru/development/razrabotchik-php...
8729,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,proektnyi-menedzher-it,management,24836,https://hirehi.ru/management/proektnyi-menedzh...
8730,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,sistemnyi-analitik,analytics,24787,https://hirehi.ru/analytics/sistemnyi-analitik...
8731,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,devops-engineer,devops,24786,https://hirehi.ru/devops/devops-engineer-24786

In [26]:
df[df["id"] == 36174]

,id,title,category,company,format,level,salary,title_trans,category_trans,id_trans,link
495,36174,графический дизайнер,design,FELINGER,удалённо,middle,~ 67 000 ₽,graficheskii-dizainer,design,36174,https://hirehi.ru/design/graficheskii-dizainer...

мы получили ссылки, но можно заметить такую проблему, что transliterate заменяет буквы не так "по-русски", в наших ссылках пишется **ux-ui-dizajner**, когда в оригинальной ссылке используется **ux-ui-dizainer**
значит библиотека не сможет "правильно" транслитерировать наш текст. Поэтому напишем словарь, с помощью которого можно будет просто заменять русскую букву на английскую, без дополнительных правил библиотеки, когда две гласные стоят рядом и происходит удвоение.

In [27]:
df.drop(columns=["title_trans", "category_trans", "id_trans"], inplace=True)
df

,id,title,category,company,format,level,salary,link
0,36677,Vue Developer,development,Сбер,гибрид Москва,middle,~ 215 000 ₽,https://hirehi.ru/development/vue-developer-36677
1,36676,Product Owner,management,Ozon,гибрид Москва,lead,~ 395 000 ₽,https://hirehi.ru/management/product-owner-36676
2,36675,Продуктовый аналитик,analytics,ВКонтакте,гибрид Москва,senior,~ 320 000 ₽,https://hirehi.ru/analytics/produktovyi-analit...
3,36674,C++ разработчик,development,Яндекс Реклама,гибрид Москва,lead,~ 411 000 ₽,https://hirehi.ru/development/c-razrabotchik-3...
4,36673,руководитель продукта,management,Ozon,гибрид Москва,lead,~ 409 000 ₽,https://hirehi.ru/management/rukovoditel-produ...
...,...,...,...,...,...,...,...,...
8727,24856,ML Engineer,development,EvApps,удалённо,middle,от 180 до 220 ₽,https://hirehi.ru/development/ml-engineer-24856
8728,24838,Разработчик PHP,development,Системы документооборота,офис Казань,senior,от 150 000 ₽,https://hirehi.ru/development/razrabotchik-php...
8729,24836,Проектный менеджер IT,management,Системы документооборота,офис Казан,junior,None,https://hirehi.ru/management/proektnyi-menedzh...
8730,24787,Системный Аналитик,analytics,iStaff-IT,удалённо по РФ,senior,от 200 000 до 285 000 ₽,https://hirehi.ru/analytics/sistemnyi-analitik...
8731,24786,DevOps engineer,devops,iStaff-IT,удалённо по РФ,senior,от 220 000 до 268 000 ₽,https://hirehi.ru/devops/devops-engineer-24786