In [87]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [88]:
df = pd.read_csv("vacancies.csv")
df.drop(columns=["Unnamed: 0"], inplace=True)
df.head()

,title,link,tags,company,time,skills,salary
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN

Итак надо поработать с тегами

In [89]:
print(type(df["tags"].iloc[0]))
str_to_parse = df["tags"].iloc[0]
print(str_to_parse)

<class 'str'>
['hybrid', 'US', 'fulltime', 'middle']

In [90]:
def str_to_list(s):
    if s.startswith("[") and s.endswith("]"):
        s = s[1:-1]
        ss = s.split(", ")
        ss = [ss.replace("'", "") for ss in ss]
        ss = [ss.replace(" ", "") for ss in ss]
        return ss
    else:
        return []


str_to_list(str_to_parse)

['hybrid', 'US', 'fulltime', 'middle']

Имба функция вроде работает попробуем ее применить

In [91]:
df["tags_parsed"] = df["tags"].apply(lambda x: str_to_list(x))
print(type(df["tags_parsed"].iloc[0]))
df.head()

<class 'list'>

,title,link,tags,company,time,skills,salary,tags_parsed
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]"
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]"
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]"
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]"
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]"

In [92]:
df["len_tags"] = df["tags_parsed"].apply(lambda x: len(x))
df.head()

,title,link,tags,company,time,skills,salary,tags_parsed,len_tags
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]",4
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]",4
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]",4
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]",3
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]",4

In [93]:
df["len_tags"].value_counts()

len_tags
4    7831
3    2294
2     365
5      48
1      15
Name: count, dtype: int64

Так значит не везде все параметры указаны, в таком случае попробуем посмотреть на те случаи, когда все 5 тега есть разберемся какие значения каждый из них принимает

In [94]:
# del skill_all
skill_all = pd.DataFrame()
print(df[df["len_tags"] > 4]["tags_parsed"].iloc[0])
skill_all["list"] = df[df["len_tags"] > 4]["tags_parsed"]
skill_all.head(10)

['remote(Europe)/hybrid', 'Portugal', 'fulltime', 'senior', 'Relocation']

                                                   list
180   [remote(Europe)/hybrid, Portugal, fulltime, se...
1173  [remote(Global)/hybrid, Serbia, fulltime, midd...
1409  [hybrid, Poland, fulltime, middle/senior, Relo...
1446       [onsite, Serbia, fulltime, lead, Relocation]
1714  [remote(Global), India, fulltime, senior, Relo...
1897     [hybrid, Poland, fulltime, middle, Relocation]
2219  [remote(Global)/hybrid/onsite, Armenia, fullti...
3388    [onsite, Ukraine, fulltime, middle, Relocation]
3406  [remote(Global)/hybrid/onsite, Serbia, fulltim...
3431  [remote/hybrid/onsite, US, fulltime, c_level, ...

In [95]:
skill_all["1_skill"] = skill_all["list"].apply(lambda x: x[0])
skill_all["2_skill"] = skill_all["list"].apply(lambda x: x[1])
skill_all["3_skill"] = skill_all["list"].apply(lambda x: x[2])
skill_all["4_skill"] = skill_all["list"].apply(lambda x: x[3])
skill_all["5_skill"] = skill_all["list"].apply(lambda x: x[4])

In [96]:
skill_all.head()

,list,1_skill,2_skill,3_skill,4_skill,5_skill
180,"[remote(Europe)/hybrid, Portugal, fulltime, se...",remote(Europe)/hybrid,Portugal,fulltime,senior,Relocation
1173,"[remote(Global)/hybrid, Serbia, fulltime, midd...",remote(Global)/hybrid,Serbia,fulltime,middle,Relocation
1409,"[hybrid, Poland, fulltime, middle/senior, Relo...",hybrid,Poland,fulltime,middle/senior,Relocation
1446,"[onsite, Serbia, fulltime, lead, Relocation]",onsite,Serbia,fulltime,lead,Relocation
1714,"[remote(Global), India, fulltime, senior, Relo...",remote(Global),India,fulltime,senior,Relocation

Кажется мы разобрались 1 это формат работы удаленка, 2 это локация, 3 это тип работы 4 это грейд 5 флаг релокации

In [97]:
print(len(skill_all))
for i in range(1, 6):
    print(f"Skill number{i}", skill_all[f"{i}_skill"].value_counts().head(3))

48
Skill number1 1_skill
remote(Europe)/hybrid           14
onsite                           9
remote(Europe)/hybrid/onsite     8
Name: count, dtype: int64
Skill number2 2_skill
Serbia    16
France    10
Poland     7
Name: count, dtype: int64
Skill number3 3_skill
fulltime    48
Name: count, dtype: int64
Skill number4 4_skill
senior           19
middle/senior     9
middle            7
Name: count, dtype: int64
Skill number5 5_skill
Relocation    48
Name: count, dtype: int64

Я изначально запутался в числе возможных тегов, их оказывается 5, а не 4, поэтому проведя анализ по 5 тегам, видим, что одно из них это relocation, соответственно просто превращаем его в флаг, есть ли relocation или нет. Для всего остального будем исследовать датасет уже с 4 тегами.

In [98]:
df["relocation"] = df["tags_parsed"].apply(lambda x: "Relocation" in x)

In [99]:
print(df["relocation"].value_counts())

relocation
False    10499
True        54
Name: count, dtype: int64

Так, с relocation вроде разобрались. Теперь уберем ее из исходного столбца tags_parsed.

In [100]:
def del_tag(l, tag):
    if tag in l:
        l.remove(tag)
    return l


df["tags_parsed"] = df["tags_parsed"].apply(lambda x: del_tag(x, "Relocation"))

In [101]:
df["len_tags"] = df["tags_parsed"].apply(lambda x: len(x))
df["len_tags"].value_counts()

len_tags
4    7873
3    2300
2     365
1      15
Name: count, dtype: int64

Ура! Уже видно какое-то движение. Теперь у нас максимум 4 тега.

In [102]:
skill_all = pd.DataFrame()
skill_all["list"] = df[df["len_tags"] > 3]["tags_parsed"]
skill_all["1_skill"] = skill_all["list"].apply(lambda x: x[0])
skill_all["2_skill"] = skill_all["list"].apply(lambda x: x[1])
skill_all["3_skill"] = skill_all["list"].apply(lambda x: x[2])
skill_all["4_skill"] = skill_all["list"].apply(lambda x: x[3])
skill_all.head()

,list,1_skill,2_skill,3_skill,4_skill
0,"[hybrid, US, fulltime, middle]",hybrid,US,fulltime,middle
1,"[onsite, US, fulltime, senior]",onsite,US,fulltime,senior
2,"[hybrid, Australia, fulltime, middle]",hybrid,Australia,fulltime,middle
4,"[onsite, Italy, fulltime, middle/senior]",onsite,Italy,fulltime,middle/senior
5,"[hybrid, US, fulltime, director]",hybrid,US,fulltime,director

Следующий на пути у нас 3

In [103]:
skill_all["3_skill"].value_counts()

3_skill
fulltime    7655
parttime     122
project       96
Name: count, dtype: int64

Замечательно теперь тогда его превращаем в столбец

In [104]:
for i in range(1, 5):
    print(f"Skill number{i}", skill_all[f"{i}_skill"].value_counts().head(10))

Skill number1 1_skill
onsite                   2691
hybrid                   1941
remote(USA)               837
remote(Russia)            436
remote(Global)            277
remote(Europe)            208
remote                    183
remote(USA)/hybrid        179
remote(Europe)/hybrid     113
remote(Russia)/hybrid      93
Name: count, dtype: int64
Skill number2 2_skill
US           2691
Russia       1455
UK            676
Poland        210
Canada        197
Germany       137
France        133
Cyprus        121
Singapore     118
Ukraine       109
Name: count, dtype: int64
Skill number3 3_skill
fulltime    7655
parttime     122
project       96
Name: count, dtype: int64
Skill number4 4_skill
senior           2586
middle           1820
middle/senior     906
lead              811
junior            404
director          397
trainee           317
head              196
senior/lead       148
c_level           127
Name: count, dtype: int64

Ну все, нигде больше он не встречается Соответственно точно заменяем эту штуку

In [105]:
def replace_tag(l, tags):
    for tag in tags:
        if tag in l:
            l.remove(tag)
            return tag
    return None

In [ ]:
employment_types = ["fulltime", "parttime", "project"]
df["employment_type"] = df["tags_parsed"].apply(
    lambda x: replace_tag(x, employment_types)
)
print(df["employment_type"].isna().sum())
df["employment_type"].value_counts()

0

employment_type
fulltime    10112
parttime      221
project       220
Name: count, dtype: int64

In [109]:
for tag in employment_types:
    df["tags_parsed"] = df["tags_parsed"].apply(lambda x: del_tag(x, tag))
df["len_tags"] = df["tags_parsed"].apply(lambda x: len(x))
df["len_tags"].value_counts()

len_tags
3    7873
2    2300
1     365
0      15
Name: count, dtype: int64

Ура! Победа! Еще один тип tag спаршен

In [111]:
skill_all = pd.DataFrame()
skill_all["list"] = df[df["len_tags"] > 2]["tags_parsed"]
skill_all["1_skill"] = skill_all["list"].apply(lambda x: x[0])
skill_all["2_skill"] = skill_all["list"].apply(lambda x: x[1])
skill_all["3_skill"] = skill_all["list"].apply(lambda x: x[2])
skill_all.head()

                             list 1_skill    2_skill        3_skill
0            [hybrid, US, middle]  hybrid         US         middle
1            [onsite, US, senior]  onsite         US         senior
2     [hybrid, Australia, middle]  hybrid  Australia         middle
4  [onsite, Italy, middle/senior]  onsite      Italy  middle/senior
5          [hybrid, US, director]  hybrid         US       director

Ну что наверное спарсим теперь 1 потом 2 а то что останется это локация

In [117]:
skill_all["1_skill"].value_counts().head(50)

1_skill
onsite                           2691
hybrid                           1941
remote(USA)                       837
remote(Russia)                    436
remote(Global)                    277
remote(Europe)                    208
remote                            183
remote(USA)/hybrid                179
remote(Europe)/hybrid             113
remote(Russia)/hybrid              93
hybrid/onsite                      89
remote(United_kingdom)             76
remote(Global)/hybrid              55
remote/hybrid                      40
remote(Poland)                     36
remote(China)                      31
remote(Canada)                     27
remote(United_kingdom)/hybrid      25
remote(Russia)/hybrid/onsite       23
remote(USA)/hybrid/onsite          20
remote(USA)/onsite                 19
remote(Europe)/hybrid/onsite       19
remote(Ukraine)                    19
onsite/hybrid                      18
remote(Spain)                      17
remote(Global)/onsite              17
remote(Portugal)                   16
remote(Russia)/onsite              15
remote(Germany)                    14
remote(Europe)/onsite              13
remote(Poland)/hybrid              13
remote(Global)/hybrid/onsite       13
remote(Brazil)                     12
remote(Belarus)                    11
remote(Germany)/hybrid             10
remote(Ireland)                     9
remote(Mexico)                      9
remote(United_states/Canada)        9
remote/hybrid/onsite                9
remote(Indonesia)                   9
remote/onsite                       8
remote(United_states)               8
remote(Sweden)                      7
remote(Ukraine)/hybrid              7
remote(Spain)/hybrid                7
remote(Australia)                   7
remote(India)                       6
remote(France)                      6
remote(Bulgaria)/hybrid             6
remote(Portugal)/hybrid             5
Name: count, dtype: int64

Вкусняшка так называемая мало того что в вакансии могут юыть сразу несколько типов так еще и страну в () храним, идея следующая сначала попаем скобки а инфу из них кладем в новый столбец потом по / сплитим и получается у нас 3 бинарных столбца (one hot encoding) onsite, hybrid, remote + еще столбец со страной.

In [131]:
def parse_work_type(l):
    country = None
    answer = {
        "onsite": False,
        "remote": False,
        "hybrid": False,
        "country": None,
        "tags": [],
    }
    parsed_tag = None
    for tag in l:
        if (
            tag.find("onsite") != -1
            or tag.find("remote") != -1
            or tag.find("hybrid") != -1
        ):
            s = tag.find("(")
            e = tag.find(")")
            if s != -1 and e != -1:
                country = tag[s + 1 : e]
                new_tag = tag[:s] + tag[e + 1 :]
                print(country, new_tag)
            else:
                country = None
                new_tag = tag
            if tag.find("onsite"):
                answer["onsite"] = True
            if tag.find("remote"):
                answer["remote"] = True
            if tag.find("hybrid"):
                answer["hybrid"] = True
            answer["country"] = country
            parsed_tag = tag
    answer["tags"] = [tag for tag in l if tag != parsed_tag]
    return answer


parse_work_type(df["tags_parsed"].iloc[5])

{'onsite': True,
 'remote': True,
 'hybrid': False,
 'country': None,
 'tags': ['US', 'director']}

In [132]:
tags = df["tags_parsed"]
for i in range(len(tags)):
    parsed = parse_work_type(tags[i])
    df.at[i, "onsite"] = parsed["onsite"]
    df.at[i, "remote"] = parsed["remote"]
    df.at[i, "hybrid"] = parsed["hybrid"]
    df.at[i, "country"] = parsed["country"]
    df.at[i, "tags_parsed"] = parsed["tags"]
df.head(20)

USA remote
USA remote
USA remote
USA remote
Global remote
United_kingdom remote/hybrid
United_kingdom remote/hybrid
United_kingdom remote/hybrid
Europe remote
United_kingdom remote/hybrid
USA remote/hybrid
USA remote/hybrid
Europe remote/hybrid
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote/hybrid
United_kingdom remote
USA remote
Global remote
USA remote/hybrid
USA remote
USA remote/hybrid
USA remote
USA remote
USA remote
USA remote
USA remote
Canada/United_states remote/hybrid
USA remote
USA remote
USA remote/hybrid
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
Global remote
Europe remote
USA remote
Germany remote
USA remote
United_kingdom remote
United_kingdom remote/hybrid
Global remote
Canada remote
United_kingdom remote
Global remote
USA remote
USA remote
USA remote
Global remote/hybrid
USA remote
Europe remote/hybrid
Global remote/hybrid
USA remote
Europe remote/hybrid
USA remote
Portugal remote/hybrid
Europe remote/onsite
Europe remote/hybrid
Europe remote/hybrid
Europe remote/hybrid
Europe remote
Europe remote/hybrid
Europe remote
Europe remote
USA remote
Global remote
Europe remote
Europe remote
Global remote
Europe remote
USA remote/onsite
USA remote
USA remote
USA remote
USA remote
USA remote
Poland remote/hybrid
USA remote/hybrid/onsite
USA remote
USA remote
USA remote
Canada remote
USA remote
USA remote
Canada remote
USA remote
USA remote
USA remote
USA remote
Germany remote
Spain remote
United_kingdom remote
Sweden remote
USA remote
USA remote
Europe remote
Ireland remote
USA remote
USA remote
Canada remote/hybrid
Global remote/hybrid
Global remote
Global remote
Brazil remote
Brazil remote
USA remote
USA remote
Canada remote
USA remote
Mexico remote
USA remote
Russia remote
Russia remote/hybrid
USA remote
Global remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
Global remote
USA remote
USA remote/hybrid
Poland remote/hybrid
USA remote
USA remote/hybrid/onsite
Global remote
USA remote/hybrid
USA remote/hybrid
Europe remote
Europe remote/hybrid/onsite
USA remote/hybrid
USA remote
USA remote
USA remote
Brazil remote
USA remote
USA remote/hybrid
USA remote
Europe remote
Europe remote
Europe remote
USA remote/onsite
USA remote
USA remote
USA remote
Canada/United_states remote/hybrid
USA remote
USA remote
USA remote
Portugal remote
Global remote
USA remote/hybrid
USA remote
USA remote
Canada remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
Spain remote
Russia remote
Russia remote
USA remote
USA remote
USA remote
USA remote
Global remote
Global remote
Global remote
Russia remote
Global remote
CIS remote/hybrid/onsite
Russia remote
USA remote
USA remote
USA remote/hybrid
USA remote
USA remote/hybrid
Global remote
USA remote
USA remote
USA remote
USA remote
Russia remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote/hybrid
Poland remote
Canada remote
USA remote
USA remote/hybrid
USA remote
Russia remote
USA remote
USA remote
USA remote
USA remote
USA remote/hybrid
USA remote/hybrid
USA remote
Canada remote
Global remote
USA remote
Global remote
Global remote
Global remote
Russia remote
Global remote
Global remote
Russia remote/hybrid
Colombia remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote/hybrid
USA remote
Russia remote
Portugal remote
Europe remote
USA remote
USA remote
Russia remote
United_kingdom remote
USA remote
Europe remote
Spain remote
Spain remote
Spain remote
Global remote
Russia remote/hybrid
Global remote
Global remote
Ukraine remote
Canada remote
USA remote
United_kingdom remote
Ireland remote
USA remote/hybrid
United_kingdom remote
United_kingdom remote
Global remote
USA remote/hybrid
United_kingdom remote
USA remote
Russia remote
Ireland remote
Ireland remote
Europe remote
Italy remote
United_kingdom remote/hybrid
USA remote
Russia remote
United_kingdom remote
USA remote
Ukraine remote
Poland remote
Ukraine remote
Ukraine remote
Ukraine remote
United_kingdom remote
Ukraine remote
Ukraine remote
Canada remote
Ukraine remote
Global remote
USA remote
Global remote
USA remote
USA remote
USA remote
USA remote
United_kingdom remote
USA remote
United_kingdom remote
USA remote
USA remote
United_kingdom remote
United_kingdom remote
USA remote/hybrid
United_kingdom remote
United_kingdom remote
United_kingdom remote
United_kingdom remote
United_kingdom remote
United_kingdom remote
Global remote
USA remote
USA remote/hybrid
United_kingdom remote/hybrid
United_kingdom remote
USA remote
USA remote
USA remote
Europe remote/hybrid
USA remote
USA remote
Russia remote
USA remote
Russia remote
USA remote
Russia remote
USA remote
Russia remote
Norway remote
USA remote/hybrid
USA remote
USA remote/onsite
USA remote
USA remote
Japan remote/onsite
Global remote
USA remote
USA remote/onsite
Global remote
Poland remote
Europe remote/hybrid
USA remote
USA remote
Global remote
Global remote
USA remote
USA remote
USA remote
Global remote
Costa_rica remote
Russia remote
USA remote
USA remote
Global remote
USA remote
USA remote
Global remote
USA remote
USA remote
USA remote
USA remote/hybrid
USA remote
Mexico remote/hybrid
USA remote
USA remote
USA remote/hybrid
USA remote/hybrid
USA remote
Europe remote
Global remote/hybrid
Global remote
Serbia remote/hybrid
India remote
Europe remote
Global remote
Russia remote/hybrid
Restricted remote
Global remote
Russia remote/hybrid
Global remote
Russia remote
Russia remote/onsite
USA remote/hybrid
United_kingdom remote
China remote
China remote
USA remote
USA remote
Global remote
Europe remote/hybrid
Russia remote
USA remote
Europe remote
USA remote
Global remote/hybrid
Russia remote/hybrid
Russia remote
Russia remote/hybrid
Russia remote/hybrid
Global remote
Global remote/hybrid
Global remote
Brazil remote
Russia remote
Georgia remote
USA remote
Russia remote
USA remote/hybrid
Russia remote
Russia remote
Global remote
Europe remote
Global remote
Global remote
Global remote
USA remote
USA remote
Global remote
USA remote/hybrid
USA remote
Global remote
Russia remote
Russia remote
USA remote
Global remote
USA remote
Canada remote
Russia remote
Global remote
Russia remote
Global remote
Turkey remote
Global remote
Global remote
USA remote
Russia remote/hybrid
Global remote/onsite
South_africa remote
United_states/Canada remote
Global remote
USA remote
Russia remote
Russia remote
Europe remote/hybrid
Global remote
Russia remote
Russia remote
Russia remote
Russia remote
Russia remote
Global remote
Russia remote
Russia remote
Global remote
Global remote
Global remote
Russia remote
USA remote
Russia remote/hybrid
Belarus remote
Global remote
USA remote
Global remote
Russia remote
Russia remote/hybrid/onsite
Russia remote/hybrid
Russia remote
Russia remote
Russia remote
Russia remote
Europe remote
Europe remote
Russia remote
Russia remote
Russia remote/hybrid/onsite
Global remote
Russia remote
Russia remote
Ukraine remote/hybrid
Russia remote
Russia remote/hybrid
Russia remote/onsite
USA remote
Global remote
Russia remote
Restricted remote
Global remote
United_kingdom remote
Global remote
Global remote
Russia remote/hybrid
Russia remote/hybrid/onsite
Poland remote
USA remote
USA remote
Europe remote
Russia remote/onsite/hybrid
Russia remote
Belarus remote
Global remote
Europe remote/hybrid
Global remote/hybrid/onsite
Latam remote
Belarus remote
Global remote
Europe remote/hybrid
Europe remote
Global remote
Russia remote
Global remote
Global remote
Global remote
Global remote
Cyprus remote/hybrid
Europe remote
Global remote
Global remote
Global remote
Global remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Global remote/hybrid/onsite
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Russia remote
Russia remote
Russia remote
Global remote
Russia remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Europe remote
Europe remote
United_states remote
Global remote
Global remote
Global remote/onsite
Global remote
Global remote
Global remote
Global remote
Global remote
USA remote
Global remote
Global remote
Europe remote
Russia remote
Russia remote
Russia remote
Russia remote
Global remote
Global remote
Global remote
Global remote
Global remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Russia remote/hybrid
Global remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Global remote
Russia remote
Global remote
Global remote
Global remote
Global remote/hybrid
Europe remote
Global remote
Global remote
Global remote
Russia remote/hybrid
Europe remote
Global remote
Global remote
Global remote
Global remote
Belarus remote
Russia remote
Europe remote
Global remote
Global remote
Belarus remote
Russia remote
Russia remote
Russia remote
Global remote
Global remote
Russia remote
Global remote
Global remote
Global remote
Global remote
Global remote
Uzbekistan remote/hybrid/onsite
Global remote
Global remote
Global remote
Global remote
Global remote
Russia remote/hybrid
Russia remote/onsite
Global remote
Russia/United_kingdom remote/hybrid
Global remote/onsite
Global remote/hybrid/onsite
Global remote
Russia remote
Global remote
Global remote
Global remote
Global remote
Russia remote
Europe remote
European_union remote
European_union remote
Russia remote
Global remote/hybrid
Russia remote
Russia remote/onsite
Global remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Europe remote
Russia remote
Russia remote
Global remote
Restricted remote
Global remote
Global remote
Global remote
Global remote
Global remote
Russia remote
Russia remote
Global remote
Global remote
Global remote
Russia remote
Global remote
Russia remote
Russia remote
Restricted remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Russia remote
Global remote
Russia remote
Global remote
Global remote
Europe remote
Europe remote
Global remote
Global remote
Global remote
Europe remote
Europe remote
Global remote
Global remote
Russia remote
Russia remote
Russia remote
Europe remote
Global remote
Europe remote
Global remote
Global remote
Europe remote
Europe remote
Global remote
Global remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Europe/Ukraine remote
Global remote
Global remote
Global remote
Restricted remote
Global remote
Russia remote
Global remote
Russia remote
Restricted remote
Russia remote
Europe remote
Global remote
Global remote
Europe remote
Global remote
Global remote
Global remote
Europe remote
Europe/Georgia remote
Russia remote
Global remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Russia remote
Global remote
Global remote
Global remote
Global remote
Global remote
Vietnam remote
Global remote
Global remote
Russia remote
Belarus remote
Global remote
Global remote
Global remote
Europe remote
Europe remote
Global remote
Global remote
MENA remote
Global remote
Global remote
Russia remote
Russia remote
Global remote
Global remote
Global remote
Russia remote
Global remote
Global remote
Global remote
Global remote
MENA remote
Global remote
Global remote
Europe remote
Global remote
Kazakhstan remote/hybrid
Europe remote
Global remote
Russia remote
Global remote
Global remote
Global remote
Russia remote
USA remote
USA remote/hybrid
Russia remote
Global remote/onsite
USA remote/hybrid
USA remote
Global remote
Global remote
Russia remote
Russia remote
Australia remote/hybrid
USA remote
USA remote/hybrid
Global remote
USA remote/onsite
Russia remote
Global remote
USA remote
USA remote
Russia remote/hybrid
USA remote
Global remote
Germany remote
Global remote
Russia remote
Global remote
USA remote
Global remote
Russia remote/hybrid
Russia remote/hybrid
Europe remote/hybrid/onsite
Europe remote/hybrid/onsite
USA remote/hybrid/onsite
Europe remote/hybrid/onsite
Global remote
USA remote/hybrid
USA remote
USA remote
USA remote
Europe remote
Russia remote
USA remote
USA remote/hybrid
USA remote/hybrid
Global remote
USA remote
Spain remote/hybrid
Portugal remote
Global remote
USA remote/hybrid
USA remote/hybrid
USA remote
Russia remote
Russia remote
Russia remote
Russia remote
United_states/Europe remote
Russia remote
USA remote
Global remote
Global remote
Global remote
Russia remote/hybrid
Global remote
Global remote/hybrid
Europe remote
Brazil remote
Canada remote
USA remote/hybrid
Global remote/hybrid/onsite
USA remote
USA remote
Global remote
USA remote
Global remote
Italy remote
Global remote
United_arab_emirates remote
USA remote
Russia remote
USA remote/hybrid
Belarus remote
Russia remote
USA remote
France remote
Europe remote
Canada remote
United_kingdom remote
Russia remote
USA remote
USA remote
USA remote/hybrid
USA remote
USA remote/hybrid/onsite
USA remote
South_korea remote
South_korea remote
USA remote/hybrid
Europe remote
USA remote/hybrid
Europe remote
USA remote
France remote
Europe remote
USA remote
Europe remote
Norway remote/hybrid
United_kingdom remote
Europe remote
Canada remote
Austria remote
USA remote
Europe remote
USA remote/hybrid
USA remote
Poland remote
South_korea remote
Europe remote
USA remote
USA remote
USA remote
France remote
USA remote
USA remote/hybrid
Global remote
Sweden remote
USA remote
USA remote
Global remote
USA remote
USA remote
USA remote
Global remote
USA remote
USA remote
Sweden remote
Europe remote
Global remote
Sweden remote
USA remote
USA remote
USA remote/hybrid
United_kingdom remote
USA remote
USA remote
Sweden remote/hybrid
USA remote
United_kingdom remote
USA remote
USA remote
Russia remote
USA remote
USA remote
USA remote
Global remote
USA remote
Global remote
USA remote
USA remote
Europe remote
Europe remote/hybrid
Global remote
Europe remote
Europe remote
Europe remote
USA remote
USA remote
USA remote
Europe remote
USA remote
Europe remote
Europe remote
USA remote
USA remote
USA remote/hybrid
USA remote
USA remote
Europe remote
Global remote
Europe remote
USA remote
Russia remote
Europe remote
Europe remote
Global remote
Global remote
Global remote
Global remote
Ukraine remote/hybrid
Russia remote
USA remote
USA remote
Europe remote/hybrid
Russia remote
Russia remote
Global remote
Global remote
Russia remote/hybrid
Russia remote
Global remote
Global remote
Global remote
Global remote
Global remote
Global remote
Europe remote
Belarus remote
Europe remote
Global remote
Russia remote
Russia remote
Russia remote/hybrid
Russia remote/hybrid/onsite
Global remote
Russia remote
Russia remote/hybrid/onsite
Russia remote/onsite
Russia remote
Russia remote/hybrid
Russia remote
Russia remote
Belarus remote
Global remote/onsite
Global remote/hybrid/onsite
Russia remote
Global remote
Global remote
Europe remote
Russia remote
Global remote
Mexico remote/hybrid
Europe remote
USA remote
Russia remote
Europe remote
USA remote
Europe remote
Russia remote/hybrid
Global remote
Russia remote/onsite
Spain remote
Spain remote/hybrid
Russia remote
Europe remote/hybrid/onsite
USA remote
Global remote
Russia remote
Global remote
Russia remote/hybrid
Global remote
Russia remote/hybrid
Global remote
Russia remote
Russia remote
Russia remote
USA remote
Russia remote
Russia remote
Russia remote/hybrid
Global remote
Russia remote
Russia remote
Russia remote
Russia remote/onsite
China remote
Global remote
Russia remote/onsite
Russia remote
Russia remote
Global remote
Global remote
Global remote/hybrid
Global remote/hybrid
Russia remote/hybrid
Russia remote
Russia remote
Europe remote
USA remote
Global remote/onsite
USA remote
Russia remote/hybrid
Russia remote
USA remote
Russia remote
Russia remote/hybrid/onsite
USA remote
USA remote
Russia remote/hybrid
Russia remote
Russia remote
Russia remote
Russia remote/hybrid
Global remote
Russia remote
Russia remote
Russia remote/hybrid
Global remote/onsite
USA remote
Global remote
USA remote
USA remote/hybrid
United_states/Canada remote/hybrid/onsite
USA remote/hybrid
Japan remote/hybrid
Japan remote
Japan remote/hybrid
Japan remote/hybrid
Japan remote
Global remote/hybrid
Europe remote/hybrid
Global remote/hybrid/onsite
Poland remote
Poland remote
Poland remote
Global remote
Poland remote
Poland remote
Poland remote
Europe remote
Czech_republic remote/hybrid
Global remote
USA remote
Global remote
Russia remote/hybrid
Global remote
Global remote
Europe remote/hybrid
Russia remote
USA remote/hybrid
USA remote/hybrid
USA remote/hybrid
Europe remote
Russia remote
China remote
USA remote
Russia remote
Global remote
United_kingdom remote
Russia remote
Global remote/hybrid
Europe remote
India remote
Russia remote
Global remote
Ireland remote
Russia remote
Russia remote
Poland remote
Russia remote
Europe remote
Romania remote
Europe remote
Europe remote
Ukraine remote
Ukraine remote
Spain remote
USA remote
USA remote
USA remote
Global remote
Russia remote
Europe remote
Russia remote/onsite
Portugal remote/hybrid
Russia remote
Russia remote
Russia remote
Russia remote
Russia remote
Global remote
Global remote
Europe remote
Global remote
Russia remote/hybrid
Europe remote
Russia remote
Russia remote/hybrid
Russia remote
Russia remote
Russia remote
Russia remote
Russia remote
USA remote
Europe remote
Global remote/hybrid/onsite
India remote
Global remote/hybrid
Russia remote
Russia remote/hybrid
Global remote
Spain remote
USA remote
Global remote
Russia remote
India remote
Russia remote
Russia remote
Global remote
Russia remote/hybrid
Russia remote/hybrid/onsite
Ireland remote/hybrid
Russia remote/hybrid
Russia remote
Global remote
Global remote
Russia remote
Russia remote/onsite
Global remote
Global remote
Russia remote/onsite
Global remote
Global remote
Global remote
Global remote
USA remote
Europe remote/hybrid
Spain remote/hybrid
Global remote/hybrid
Global remote
USA remote/hybrid
Global remote
Europe remote/hybrid
Europe remote/hybrid
Global remote
Global remote
Russia remote
Russia remote/onsite/hybrid
Global remote/hybrid
Russia remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
Global remote/hybrid
USA remote
USA remote/hybrid
Russia remote
Global remote/hybrid
Canada remote
Russia remote
Russia remote
Global remote
Germany remote/hybrid
New_zealand remote/hybrid
USA remote/hybrid/onsite
Global remote
Global remote
Global remote
Global remote/hybrid/onsite
Kazakhstan remote/hybrid
Russia remote
Russia remote
Russia remote
Russia remote
Russia remote/hybrid
Russia remote
Russia remote
Russia remote
Russia remote
Europe remote
Russia remote/hybrid
Global remote
Russia remote
Russia remote
Belarus remote/hybrid
Europe remote/hybrid
Europe remote/hybrid/onsite
Global remote
Global remote/hybrid
Russia remote/hybrid/onsite
Russia remote
Russia remote
Global remote/hybrid
Global remote
Russia remote
Russia remote
Russia remote
Global remote
Russia remote
Global remote
Global remote
Russia remote
Global remote
Russia remote
Global remote
Global remote/hybrid/onsite
USA remote
USA remote
Global remote
USA remote
USA remote/hybrid
USA remote/hybrid
Canada remote/hybrid
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
Russia remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote
USA remote/hybrid
USA remote
USA remote
United_kingdom remote
USA remote
USA remote
Global remote
Global remote

,title,link,tags,company,time,skills,salary,tags_parsed,len_tags,relocation,employment_type,onsite,remote,hybrid,country
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[US, middle]",3,False,fulltime,True,True,False,None
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[US, senior]",3,False,fulltime,False,True,True,None
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[Australia, middle]",3,False,fulltime,True,True,False,None
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,[Australia],2,False,fulltime,True,True,False,None
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[Italy, middle/senior]",3,False,fulltime,False,True,True,None
5,"Vp, Real Estate Strategy & Planning",https://hirify.me/jobs/440674-real-estate-stra...,"['hybrid', 'US', 'fulltime', 'director']",Company hidden,14 minutes ago,"['finance', 'real estate', 'strategy', 'progra...",NaN,"[US, director]",3,False,fulltime,True,True,False,None
6,Gps Sales Onboarding & Strategic Programs Lead,https://hirify.me/jobs/440673-gps-sales-onboar...,"['remote (USA)', 'US', 'fulltime', 'lead']",Company hidden,14 minutes ago,"['crm', 'sales', 'b2b', 'tableau', 'program ma...",NaN,"[US, lead]",3,False,fulltime,True,False,True,USA
7,"Partner Strategy & Operations, Senior Manager",https://hirify.me/jobs/440672-partner-strategy...,"['remote (USA)', 'US', 'fulltime', 'senior']",Company hidden,14 minutes ago,"['sql', 'snowflake', 'excel', 'finance', 'tabl...",NaN,"[US, senior]",3,False,fulltime,True,False,True,USA
8,"Manager, Government Procurement & Process Stra...",https://hirify.me/jobs/440671-government-procu...,"['remote (USA)', 'US', 'fulltime', 'middle']",Company hidden,15 minutes ago,"['erp', 'salesforce', 'google sheets', 'saas',...",NaN,"[US, middle]",3,False,fulltime,True,False,True,USA
9,"Director, Strategic Workforce Planner",https://hirify.me/jobs/440670-strategic-workfo...,"['onsite', 'US', 'fulltime', 'director']",Company hidden,15 minutes ago,"['ai', 'data analysis', 'hr strategy', 'tablea...",NaN,"[US, director]",3,False,fulltime,False,True,True,None
10,Strategic Solution Engineer (AI),https://hirify.me/jobs/440669-strategic-soluti...,"['onsite', 'Austria', 'fulltime', 'middle/seni...",Company hidden,16 minutes ago,"['ai', 'data', 'cloud', 'solution architecture...",NaN,"[Austria, middle/senior]",3,False,fulltime,False,True,True,None
11,Fins Strategic Account Leader (Fintech),https://hirify.me/jobs/440668-strategic-accoun...,"['onsite', 'Singapore', 'fulltime', 'lead']",Company hidden,17 minutes ago,"['sales', 'account management', 'saas', 'big d...",NaN,"[Singapore, lead]",3,False,fulltime,False,True,True,None
12,Software Development Engineer (AI),https://hirify.me/jobs/440667-software-develop...,"['onsite', 'US', 'fulltime', 'middle']",Company hidden,18 minutes ago,"['ai', 'ml', 'python', 'aws', 'automation', '+...",143 700 - 194 400\n$,"[US, middle]",3,False,fulltime,False,True,True,None
13,"Regional Director, Commercial Sales (AI)",https://hirify.me/jobs/440666-regional-directo...,"['remote', 'fulltime', 'director']",Company hidden,19 minutes ago,"['sales', 'ai', 'communication', 'forecasting'...",NaN,[director],2,False,fulltime,True,False,True,None
14,"Engineering Manager, Core Services (AI)",https://hirify.me/jobs/440665-engineering-mana...,"['fulltime', 'lead']",Company hidden,19 minutes ago,"['ai', 'backend', 'api', 'distributed systems'...",NaN,[lead],1,False,fulltime,False,False,False,None
15,Benefits Specialist,https://hirify.me/jobs/440605-benefits-special...,"['remote (USA)', 'US', 'fulltime', 'middle']",Company hidden,21 minutes ago,"['ai', 'compliance', 'hris', 'employee support...",55 000 - 75 000\n$,"[US, middle]",3,False,fulltime,True,False,True,USA
16,Account Manager,https://hirify.me/jobs/440606-account-manager-...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,21 minutes ago,"['startup experience', 'ai', 'project manageme...",70 000 - 100 000\n$,"[US, middle]",3,False,fulltime,True,True,False,None
17,Associate Systems Engineer,https://hirify.me/jobs/440604-associate-system...,"['onsite', 'US', 'fulltime', 'junior']",Company hidden,22 minutes ago,"['scripting', 'linux', 'networking', 'vmware',...",NaN,"[US, junior]",3,False,fulltime,False,True,True,None
18,Crypto SEO Content Writer (DeFi/AI),https://hirify.me/jobs/429150-crypto-seo-conte...,"['remote (Global)', 'parttime', 'middle']",OmniRisk,updated 25 minutes ago,"['ai', 'seo', 'blockchain', 'web3', 'risk mana...",15 - 25\n$,[middle],2,False,parttime,True,False,True,Global
19,Data Scientist (Healthcare),https://hirify.me/jobs/434275-data-scientist-h...,"['remote (United_kingdom)/hybrid', 'UK', 'full...",Company hidden,updated 1 hour ago,"['ai', 'python', 'sql', 'flask', 'data visuali...",45 000\nGBP,"[UK, middle/senior]",3,False,fulltime,True,False,True,United_kingdom

In [133]:
df["len_tags"] = df["tags_parsed"].apply(lambda x: len(x))
df["len_tags"].value_counts()

len_tags
2    7903
1    2319
0     331
Name: count, dtype: int64

In [135]:
skill_all["3_skill"].value_counts().head(50)

3_skill
senior                          2586
middle                          1820
middle/senior                    906
lead                             811
junior                           404
director                         397
trainee                          317
head                             196
senior/lead                      148
c_level                          127
junior/middle                     97
trainee/junior                    11
junior/middle/senior              10
lead/director                      7
middle/lead                        5
junior/senior                      5
middle/senior/lead                 4
director/c_level                   4
head/director                      3
trainee/junior/middle/senior       3
lead/head                          2
senior/director                    2
lead/c_level                       2
junior/middle/senior/lead          2
trainee/middle                     1
senior/head                        1
senior/lead/director               1
senior/lead/head                   1
Name: count, dtype: int64

In [139]:
un = skill_all["3_skill"].unique()
un

<StringArray>
[                      'middle',                       'senior',
                'middle/senior',                     'director',
                         'lead',                       'junior',
                  'senior/lead',                         'head',
                      'trainee',                'junior/middle',
               'trainee/junior',                      'c_level',
                'lead/director',           'middle/senior/lead',
                  'middle/lead',                    'lead/head',
                'head/director',               'trainee/middle',
             'director/c_level',                'junior/senior',
         'junior/middle/senior', 'trainee/junior/middle/senior',
              'senior/director',                 'lead/c_level',
                  'senior/head',         'senior/lead/director',
    'junior/middle/senior/lead',             'senior/lead/head']
Length: 28, dtype: str

In [141]:
new_un = []
for i in un:
    if i.find("/") != -1:
        new_un.extend(i.split("/"))
print(len(new_un))
new_un = set(new_un)
print(len(new_un))
print(new_un)

48
8
{'lead', 'c_level', 'senior', 'director', 'trainee', 'head', 'middle', 'junior'}

In [143]:
def parse_level_type(l):
    answer = {
        "tags": l,
        "lead": False,
        "c_level": False,
        "senior": False,
        "director": False,
        "trainee": False,
        "head": False,
        "middle": False,
        "junior": False,
    }
    parsed_tag = None
    for tag in l:
        if tag.find("lead") != -1:
            answer["lead"] = True
            parsed_tag = tag
        if tag.find("c_level") != -1:
            answer["c_level"] = True
            parsed_tag = tag
        if tag.find("senior") != -1:
            answer["senior"] = True
            parsed_tag = tag
        if tag.find("director") != -1:
            answer["director"] = True
            parsed_tag = tag
        if tag.find("trainee") != -1:
            answer["trainee"] = True
            parsed_tag = tag
        if tag.find("head") != -1:
            answer["head"] = True
            parsed_tag = tag
        if tag.find("middle") != -1:
            answer["middle"] = True
            parsed_tag = tag
        if tag.find("junior") != -1:
            answer["junior"] = True
            parsed_tag = tag
    answer["tags"] = [tag for tag in l if tag != parsed_tag]
    return answer


parse_level_type(df["tags_parsed"].iloc[5])

{'tags': ['US'],
 'lead': False,
 'c_level': False,
 'senior': False,
 'director': True,
 'trainee': False,
 'head': False,
 'middle': False,
 'junior': False}

In [144]:
tags = df["tags_parsed"]
for i in range(len(tags)):
    parsed = parse_level_type(tags[i])
    df.at[i, "lead"] = parsed["lead"]
    df.at[i, "c_level"] = parsed["c_level"]
    df.at[i, "senior"] = parsed["senior"]
    df.at[i, "director"] = parsed["director"]
    df.at[i, "trainee"] = parsed["trainee"]
    df.at[i, "head"] = parsed["head"]
    df.at[i, "middle"] = parsed["middle"]
    df.at[i, "junior"] = parsed["junior"]
    df.at[i, "tags_parsed"] = parsed["tags"]
df.head(20)

,title,link,tags,company,time,skills,salary,tags_parsed,len_tags,relocation,...,hybrid,country,lead,c_level,senior,director,trainee,head,middle,junior
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,[US],2,False,...,False,None,False,False,False,False,False,False,True,False
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,[US],2,False,...,True,None,False,False,True,False,False,False,False,False
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,[Australia],2,False,...,False,None,False,False,False,False,False,False,True,False
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,[Australia],1,False,...,False,None,False,False,False,False,False,False,False,False
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,[Italy],2,False,...,True,None,False,False,True,False,False,False,True,False
5,"Vp, Real Estate Strategy & Planning",https://hirify.me/jobs/440674-real-estate-stra...,"['hybrid', 'US', 'fulltime', 'director']",Company hidden,14 minutes ago,"['finance', 'real estate', 'strategy', 'progra...",NaN,[US],2,False,...,False,None,False,False,False,True,False,False,False,False
6,Gps Sales Onboarding & Strategic Programs Lead,https://hirify.me/jobs/440673-gps-sales-onboar...,"['remote (USA)', 'US', 'fulltime', 'lead']",Company hidden,14 minutes ago,"['crm', 'sales', 'b2b', 'tableau', 'program ma...",NaN,[US],2,False,...,True,USA,True,False,False,False,False,False,False,False
7,"Partner Strategy & Operations, Senior Manager",https://hirify.me/jobs/440672-partner-strategy...,"['remote (USA)', 'US', 'fulltime', 'senior']",Company hidden,14 minutes ago,"['sql', 'snowflake', 'excel', 'finance', 'tabl...",NaN,[US],2,False,...,True,USA,False,False,True,False,False,False,False,False
8,"Manager, Government Procurement & Process Stra...",https://hirify.me/jobs/440671-government-procu...,"['remote (USA)', 'US', 'fulltime', 'middle']",Company hidden,15 minutes ago,"['erp', 'salesforce', 'google sheets', 'saas',...",NaN,[US],2,False,...,True,USA,False,False,False,False,False,False,True,False
9,"Director, Strategic Workforce Planner",https://hirify.me/jobs/440670-strategic-workfo...,"['onsite', 'US', 'fulltime', 'director']",Company hidden,15 minutes ago,"['ai', 'data analysis', 'hr strategy', 'tablea...",NaN,[US],2,False,...,True,None,False,False,False,True,False,False,False,False
10,Strategic Solution Engineer (AI),https://hirify.me/jobs/440669-strategic-soluti...,"['onsite', 'Austria', 'fulltime', 'middle/seni...",Company hidden,16 minutes ago,"['ai', 'data', 'cloud', 'solution architecture...",NaN,[Austria],2,False,...,True,None,False,False,True,False,False,False,True,False
11,Fins Strategic Account Leader (Fintech),https://hirify.me/jobs/440668-strategic-accoun...,"['onsite', 'Singapore', 'fulltime', 'lead']",Company hidden,17 minutes ago,"['sales', 'account management', 'saas', 'big d...",NaN,[Singapore],2,False,...,True,None,True,False,False,False,False,False,False,False
12,Software Development Engineer (AI),https://hirify.me/jobs/440667-software-develop...,"['onsite', 'US', 'fulltime', 'middle']",Company hidden,18 minutes ago,"['ai', 'ml', 'python', 'aws', 'automation', '+...",143 700 - 194 400\n$,[US],2,False,...,True,None,False,False,False,False,False,False,True,False
13,"Regional Director, Commercial Sales (AI)",https://hirify.me/jobs/440666-regional-directo...,"['remote', 'fulltime', 'director']",Company hidden,19 minutes ago,"['sales', 'ai', 'communication', 'forecasting'...",NaN,[],1,False,...,True,None,False,False,False,True,False,False,False,False
14,"Engineering Manager, Core Services (AI)",https://hirify.me/jobs/440665-engineering-mana...,"['fulltime', 'lead']",Company hidden,19 minutes ago,"['ai', 'backend', 'api', 'distributed systems'...",NaN,[],1,False,...,False,None,True,False,False,False,False,False,False,False
15,Benefits Specialist,https://hirify.me/jobs/440605-benefits-special...,"['remote (USA)', 'US', 'fulltime', 'middle']",Company hidden,21 minutes ago,"['ai', 'compliance', 'hris', 'employee support...",55 000 - 75 000\n$,[US],2,False,...,True,USA,False,False,False,False,False,False,True,False
16,Account Manager,https://hirify.me/jobs/440606-account-manager-...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,21 minutes ago,"['startup experience', 'ai', 'project manageme...",70 000 - 100 000\n$,[US],2,False,...,False,None,False,False,False,False,False,False,True,False
17,Associate Systems Engineer,https://hirify.me/jobs/440604-associate-system...,"['onsite', 'US', 'fulltime', 'junior']",Company hidden,22 minutes ago,"['scripting', 'linux', 'networking', 'vmware',...",NaN,[US],2,False,...,True,None,False,False,False,False,False,False,False,True
18,Crypto SEO Content Writer (DeFi/AI),https://hirify.me/jobs/429150-crypto-seo-conte...,"['remote (Global)', 'parttime', 'middle']",OmniRisk,updated 25 minutes ago,"['ai', 'seo', 'blockchain', 'web3', 'risk mana...",15 - 25\n$,[],1,False,...,True,Global,False,False,False,False,False,False,True,False
19,Data Scientist (Healthcare),https://hirify.me/jobs/434275-data-scientist-h...,"['remote (United_kingdom)/hybrid', 'UK', 'full...",Company hidden,updated 1 hour ago,"['ai', 'python', 'sql', 'flask', 'data visuali...",45 000\nGBP,[UK],2,False,...,True,United_kingdom,False,False,True,False,False,False,True,False

In [145]:
df.to_csv("vacancies_cleaned.csv", index=False)