In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('vacancies.csv')

In [3]:
df.head()

,Unnamed: 0,title,link,tags,company,time,skills,salary
0,0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$
1,1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN
2,2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN
3,3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD
4,4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN

In [4]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [5]:
df.head()

,title,link,tags,company,time,skills,salary
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN

Итак надо поработать с тегами

In [6]:
type(df['tags'].iloc[0])

str

In [7]:
str_to_parse = df['tags'].iloc[0]

In [8]:
str_to_parse

"['hybrid', 'US', 'fulltime', 'middle']"

In [9]:
def str_to_list(s):
    if s.startswith('[') and s.endswith(']'):
        s = s[1:-1]
        ss = s.split(', ')
        ss = [ss.replace("'", "") for ss in ss]
        ss = [ss.replace(' ', '') for ss in ss]
        return ss
    else:
        return []

In [10]:
str_to_list(str_to_parse)

['hybrid', 'US', 'fulltime', 'middle']

Имба функция вроде работает попробуем ее применить

In [14]:
df['tags_parsed'] = df['tags'].apply(lambda x: str_to_list(x))

In [15]:
type(df['tags_parsed'].iloc[0])

list

In [16]:
df.head()

,title,link,tags,company,time,skills,salary,tags_parsed
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]"
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]"
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]"
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]"
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]"

In [17]:
df['len_skills']= df['tags_parsed'].apply(lambda x: len(x))

In [18]:
df.head()

,title,link,tags,company,time,skills,salary,tags_parsed,len_skills
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]",4
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]",4
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]",4
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]",3
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]",4

In [19]:
df['len_skills'].value_counts()

len_skills
4    7831
3    2294
2     365
5      48
1      15
Name: count, dtype: int64

Так значит не везде все параметры указаны, в таком случае попробуем посмотреть на те случаи, когда все 4 тега есть разберемся какие значения каждый из них принимает