In [87]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [88]:
df = pd.read_csv('vacancies.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

,title,link,tags,company,time,skills,salary
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN

Итак надо поработать с тегами

In [89]:
print(type(df['tags'].iloc[0]))
str_to_parse = df['tags'].iloc[0]
print(str_to_parse)

<class 'str'>
['hybrid', 'US', 'fulltime', 'middle']

In [90]:
def str_to_list(s):
    if s.startswith('[') and s.endswith(']'):
        s = s[1:-1]
        ss = s.split(', ')
        ss = [ss.replace("'", "") for ss in ss]
        ss = [ss.replace(' ', '') for ss in ss]
        return ss
    else:
        return []

str_to_list(str_to_parse)

['hybrid', 'US', 'fulltime', 'middle']

Имба функция вроде работает попробуем ее применить

In [91]:
df['tags_parsed'] = df['tags'].apply(lambda x: str_to_list(x))
print(type(df['tags_parsed'].iloc[0]))
df.head()

<class 'list'>

,title,link,tags,company,time,skills,salary,tags_parsed
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]"
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]"
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]"
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]"
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]"

In [92]:
df['len_tags']= df['tags_parsed'].apply(lambda x: len(x))
df.head()

,title,link,tags,company,time,skills,salary,tags_parsed,len_tags
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]",4
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]",4
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]",4
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]",3
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]",4

In [93]:
df['len_tags'].value_counts()

len_tags
4    7831
3    2294
2     365
5      48
1      15
Name: count, dtype: int64

Так значит не везде все параметры указаны, в таком случае попробуем посмотреть на те случаи, когда все 5 тега есть разберемся какие значения каждый из них принимает

In [94]:
#del skill_all
skill_all = pd.DataFrame()
print(df[df['len_tags'] > 4]['tags_parsed'].iloc[0])
skill_all['list'] = df[df['len_tags'] > 4]['tags_parsed']
skill_all.head(10)

['remote(Europe)/hybrid', 'Portugal', 'fulltime', 'senior', 'Relocation']

                                                   list
180   [remote(Europe)/hybrid, Portugal, fulltime, se...
1173  [remote(Global)/hybrid, Serbia, fulltime, midd...
1409  [hybrid, Poland, fulltime, middle/senior, Relo...
1446       [onsite, Serbia, fulltime, lead, Relocation]
1714  [remote(Global), India, fulltime, senior, Relo...
1897     [hybrid, Poland, fulltime, middle, Relocation]
2219  [remote(Global)/hybrid/onsite, Armenia, fullti...
3388    [onsite, Ukraine, fulltime, middle, Relocation]
3406  [remote(Global)/hybrid/onsite, Serbia, fulltim...
3431  [remote/hybrid/onsite, US, fulltime, c_level, ...

In [95]:
skill_all['1_skill'] = skill_all['list'].apply(lambda x: x[0])
skill_all['2_skill'] = skill_all['list'].apply(lambda x: x[1])
skill_all['3_skill'] = skill_all['list'].apply(lambda x: x[2])
skill_all['4_skill'] = skill_all['list'].apply(lambda x: x[3])
skill_all['5_skill'] = skill_all['list'].apply(lambda x: x[4])

In [96]:
skill_all.head()

,list,1_skill,2_skill,3_skill,4_skill,5_skill
180,"[remote(Europe)/hybrid, Portugal, fulltime, se...",remote(Europe)/hybrid,Portugal,fulltime,senior,Relocation
1173,"[remote(Global)/hybrid, Serbia, fulltime, midd...",remote(Global)/hybrid,Serbia,fulltime,middle,Relocation
1409,"[hybrid, Poland, fulltime, middle/senior, Relo...",hybrid,Poland,fulltime,middle/senior,Relocation
1446,"[onsite, Serbia, fulltime, lead, Relocation]",onsite,Serbia,fulltime,lead,Relocation
1714,"[remote(Global), India, fulltime, senior, Relo...",remote(Global),India,fulltime,senior,Relocation

Кажется мы разобрались 1 это формат работы удаленка, 2 это локация, 3 это тип работы 4 это грейд 5 флаг релокации

In [97]:
print(len(skill_all))
for i in range(1,6):
    print(f'Skill number{i}', skill_all[f'{i}_skill'].value_counts().head(3))

48
Skill number1 1_skill
remote(Europe)/hybrid           14
onsite                           9
remote(Europe)/hybrid/onsite     8
Name: count, dtype: int64
Skill number2 2_skill
Serbia    16
France    10
Poland     7
Name: count, dtype: int64
Skill number3 3_skill
fulltime    48
Name: count, dtype: int64
Skill number4 4_skill
senior           19
middle/senior     9
middle            7
Name: count, dtype: int64
Skill number5 5_skill
Relocation    48
Name: count, dtype: int64

Я изначально запутался в числе возможных тегов, их оказывается 5, а не 4, поэтому проведя анализ по 5 тегам, видим, что одно из них это relocation, соответственно просто превращаем его в флаг, есть ли relocation или нет. Для всего остального будем исследовать датасет уже с 4 тегами.

In [98]:
df['relocation'] = df['tags_parsed'].apply(lambda x: 'Relocation' in x)

In [99]:
print(df['relocation'].value_counts())

relocation
False    10499
True        54
Name: count, dtype: int64

Так, с relocation вроде разобрались. Теперь уберем ее из исходного столбца tags_parsed.

In [100]:
def del_tag(l, tag):
    if tag in l:
        l.remove(tag)
    return l

df['tags_parsed'] = df['tags_parsed'].apply(lambda x: del_tag(x, 'Relocation'))

In [101]:
df['len_tags']= df['tags_parsed'].apply(lambda x: len(x))
df['len_tags'].value_counts()

len_tags
4    7873
3    2300
2     365
1      15
Name: count, dtype: int64

Ура! Уже видно какое-то движение. Теперь у нас максимум 4 тега.

In [102]:
skill_all = pd.DataFrame()
skill_all['list'] = df[df['len_tags'] > 3]['tags_parsed']
skill_all['1_skill'] = skill_all['list'].apply(lambda x: x[0])
skill_all['2_skill'] = skill_all['list'].apply(lambda x: x[1])
skill_all['3_skill'] = skill_all['list'].apply(lambda x: x[2])
skill_all['4_skill'] = skill_all['list'].apply(lambda x: x[3])
skill_all.head()

,list,1_skill,2_skill,3_skill,4_skill
0,"[hybrid, US, fulltime, middle]",hybrid,US,fulltime,middle
1,"[onsite, US, fulltime, senior]",onsite,US,fulltime,senior
2,"[hybrid, Australia, fulltime, middle]",hybrid,Australia,fulltime,middle
4,"[onsite, Italy, fulltime, middle/senior]",onsite,Italy,fulltime,middle/senior
5,"[hybrid, US, fulltime, director]",hybrid,US,fulltime,director

Следующий на пути у нас 3

In [103]:
skill_all['3_skill'].value_counts()

3_skill
fulltime    7655
parttime     122
project       96
Name: count, dtype: int64

Замечательно теперь тогда его превращаем в столбец

In [104]:
for i in range(1,5):
    print(f'Skill number{i}', skill_all[f'{i}_skill'].value_counts().head(10))

Skill number1 1_skill
onsite                   2691
hybrid                   1941
remote(USA)               837
remote(Russia)            436
remote(Global)            277
remote(Europe)            208
remote                    183
remote(USA)/hybrid        179
remote(Europe)/hybrid     113
remote(Russia)/hybrid      93
Name: count, dtype: int64
Skill number2 2_skill
US           2691
Russia       1455
UK            676
Poland        210
Canada        197
Germany       137
France        133
Cyprus        121
Singapore     118
Ukraine       109
Name: count, dtype: int64
Skill number3 3_skill
fulltime    7655
parttime     122
project       96
Name: count, dtype: int64
Skill number4 4_skill
senior           2586
middle           1820
middle/senior     906
lead              811
junior            404
director          397
trainee           317
head              196
senior/lead       148
c_level           127
Name: count, dtype: int64

Ну все, нигде больше он не встречается Соответственно точно заменяем эту штуку

In [105]:
def replace_tag(l, tags):
    for tag in tags:
        if tag in l:
            l.remove(tag)
            return tag
    return None

In [ ]:
employment_types = ['fulltime', 'parttime', 'project']
df['employment_type'] = df['tags_parsed'].apply(lambda x: replace_tag(x, employment_types))
print(df['employment_type'].isna().sum())
df['employment_type'].value_counts()

0

employment_type
fulltime    10112
parttime      221
project       220
Name: count, dtype: int64

In [109]:
for tag in employment_types:    
    df['tags_parsed'] = df['tags_parsed'].apply(lambda x: del_tag(x, tag))
df['len_tags']= df['tags_parsed'].apply(lambda x: len(x))
df['len_tags'].value_counts()

len_tags
3    7873
2    2300
1     365
0      15
Name: count, dtype: int64

Ура! Победа! Еще один тип tag спаршен

In [111]:
skill_all = pd.DataFrame()
skill_all['list'] = df[df['len_tags'] > 2]['tags_parsed']
skill_all['1_skill'] = skill_all['list'].apply(lambda x: x[0])
skill_all['2_skill'] = skill_all['list'].apply(lambda x: x[1])
skill_all['3_skill'] = skill_all['list'].apply(lambda x: x[2])
skill_all.head()

                             list 1_skill    2_skill        3_skill
0            [hybrid, US, middle]  hybrid         US         middle
1            [onsite, US, senior]  onsite         US         senior
2     [hybrid, Australia, middle]  hybrid  Australia         middle
4  [onsite, Italy, middle/senior]  onsite      Italy  middle/senior
5          [hybrid, US, director]  hybrid         US       director

Ну что наверное спарсим теперь 1 потом 2 а то что останется это локация

In [114]:
skill_all['1_skill'].value_counts().head(50)

1_skill
onsite                           2691
hybrid                           1941
remote(USA)                       837
remote(Russia)                    436
remote(Global)                    277
remote(Europe)                    208
remote                            183
remote(USA)/hybrid                179
remote(Europe)/hybrid             113
remote(Russia)/hybrid              93
hybrid/onsite                      89
remote(United_kingdom)             76
remote(Global)/hybrid              55
remote/hybrid                      40
remote(Poland)                     36
remote(China)                      31
remote(Canada)                     27
remote(United_kingdom)/hybrid      25
remote(Russia)/hybrid/onsite       23
remote(USA)/hybrid/onsite          20
remote(USA)/onsite                 19
remote(Europe)/hybrid/onsite       19
remote(Ukraine)                    19
onsite/hybrid                      18
remote(Spain)                      17
remote(Global)/onsite              17
remote(Portugal)                   16
remote(Russia)/onsite              15
remote(Germany)                    14
remote(Europe)/onsite              13
remote(Poland)/hybrid              13
remote(Global)/hybrid/onsite       13
remote(Brazil)                     12
remote(Belarus)                    11
remote(Germany)/hybrid             10
remote(Ireland)                     9
remote(Mexico)                      9
remote(United_states/Canada)        9
remote/hybrid/onsite                9
remote(Indonesia)                   9
remote/onsite                       8
remote(United_states)               8
remote(Sweden)                      7
remote(Ukraine)/hybrid              7
remote(Spain)/hybrid                7
remote(Australia)                   7
remote(India)                       6
remote(France)                      6
remote(Bulgaria)/hybrid             6
remote(Portugal)/hybrid             5
Name: count, dtype: int64

Вкусняшка так называемая мало того что в вакансии могут юыть сразу несколько типов так еще и страну в () храним, идея следующая сначала попаем скобки а инфу из них кладем в новый столбец потом по / сплитим и получается у нас 3 бинарных столбца (one hot encoding) onsite, hybrid, remote + еще столбец со страной.