In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('vacancies.csv')

In [3]:
df.head()

,Unnamed: 0,title,link,tags,company,time,skills,salary
0,0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$
1,1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN
2,2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN
3,3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD
4,4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN

In [4]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [5]:
df.head()

,title,link,tags,company,time,skills,salary
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN

Итак надо поработать с тегами

In [6]:
type(df['tags'].iloc[0])

str

In [7]:
str_to_parse = df['tags'].iloc[0]

In [8]:
str_to_parse

"['hybrid', 'US', 'fulltime', 'middle']"

In [9]:
def str_to_list(s):
    if s.startswith('[') and s.endswith(']'):
        s = s[1:-1]
        ss = s.split(', ')
        ss = [ss.replace("'", "") for ss in ss]
        ss = [ss.replace(' ', '') for ss in ss]
        return ss
    else:
        return []

In [10]:
str_to_list(str_to_parse)

['hybrid', 'US', 'fulltime', 'middle']

Имба функция вроде работает попробуем ее применить

In [14]:
df['tags_parsed'] = df['tags'].apply(lambda x: str_to_list(x))

In [15]:
type(df['tags_parsed'].iloc[0])

list

In [16]:
df.head()

,title,link,tags,company,time,skills,salary,tags_parsed
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]"
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]"
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]"
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]"
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]"

In [17]:
df['len_skills']= df['tags_parsed'].apply(lambda x: len(x))

In [18]:
df.head()

,title,link,tags,company,time,skills,salary,tags_parsed,len_skills
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,31 seconds ago,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,"[hybrid, US, fulltime, middle]",4
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,2 minutes ago,"['sales', 'account management', 'salesforce', ...",NaN,"[onsite, US, fulltime, senior]",4
2,Forward-Deployed Data Scientist II (AI),https://hirify.me/jobs/440677-data-scientist-a...,"['hybrid', 'Australia', 'fulltime', 'middle']",Company hidden,3 minutes ago,"['ai', 'python', 'sql', 'kubernetes', 'pandas'...",NaN,"[hybrid, Australia, fulltime, middle]",4
3,Customer Support Specialist (AI),https://hirify.me/jobs/440676-customer-support...,"['hybrid', 'Australia', 'fulltime']",Company hidden,5 minutes ago,"['ai', 'communication skills', 'customer servi...",62 600 - 84 800\nAUD,"[hybrid, Australia, fulltime]",3
4,Deal Strategy And Pricing Manager (Fintech),https://hirify.me/jobs/440675-deal-strategy-pr...,"['onsite', 'Italy', 'fulltime', 'middle/senior']",Company hidden,13 minutes ago,"['communication skills', 'italian', 'analytica...",NaN,"[onsite, Italy, fulltime, middle/senior]",4

In [19]:
df['len_skills'].value_counts()

len_skills
4    7831
3    2294
2     365
5      48
1      15
Name: count, dtype: int64

Так значит не везде все параметры указаны, в таком случае попробуем посмотреть на те случаи, когда все 4 тега есть разберемся какие значения каждый из них принимает

In [30]:
skill_all = []

In [38]:
#del skill_all
skill_all = pd.DataFrame()

In [48]:
df[df['len_skills'] > 4]['tags_parsed'].iloc[0]

['remote(Europe)/hybrid', 'Portugal', 'fulltime', 'senior', 'Relocation']

In [49]:
skill_all['list'] = df[df['len_skills'] > 4]['tags_parsed']

In [40]:
skill_all.head(10)

                                                   list
180   [remote(Europe)/hybrid, Portugal, fulltime, se...
1173  [remote(Global)/hybrid, Serbia, fulltime, midd...
1409  [hybrid, Poland, fulltime, middle/senior, Relo...
1446       [onsite, Serbia, fulltime, lead, Relocation]
1714  [remote(Global), India, fulltime, senior, Relo...
1897     [hybrid, Poland, fulltime, middle, Relocation]
2219  [remote(Global)/hybrid/onsite, Armenia, fullti...
3388    [onsite, Ukraine, fulltime, middle, Relocation]
3406  [remote(Global)/hybrid/onsite, Serbia, fulltim...
3431  [remote/hybrid/onsite, US, fulltime, c_level, ...

In [50]:
skill_all['1_skill'] = skill_all['list'].apply(lambda x: x[0])
skill_all['2_skill'] = skill_all['list'].apply(lambda x: x[1])
skill_all['3_skill'] = skill_all['list'].apply(lambda x: x[2])
skill_all['4_skill'] = skill_all['list'].apply(lambda x: x[3])
skill_all['5_skill'] = skill_all['list'].apply(lambda x: x[4])

In [51]:
skill_all.head()

,list,1_skill,2_skill,3_skill,4_skill,5_skill
180,"[remote(Europe)/hybrid, Portugal, fulltime, se...",remote(Europe)/hybrid,Portugal,fulltime,senior,Relocation
1173,"[remote(Global)/hybrid, Serbia, fulltime, midd...",remote(Global)/hybrid,Serbia,fulltime,middle,Relocation
1409,"[hybrid, Poland, fulltime, middle/senior, Relo...",hybrid,Poland,fulltime,middle/senior,Relocation
1446,"[onsite, Serbia, fulltime, lead, Relocation]",onsite,Serbia,fulltime,lead,Relocation
1714,"[remote(Global), India, fulltime, senior, Relo...",remote(Global),India,fulltime,senior,Relocation

Кажется мы разобрались 1 это формат работы удаленка, 2 это локация, 3 это тип работы 4 это грейд

In [46]:
len(skill_all)

48

In [53]:
for i in range(1,6):
    print(f'Skill number{i}', skill_all[f'{i}_skill'].value_counts())

Skill number1 1_skill
remote(Europe)/hybrid           14
onsite                           9
remote(Europe)/hybrid/onsite     8
hybrid                           5
remote(Global)/hybrid            4
remote(Global)                   3
remote(Global)/hybrid/onsite     2
remote/hybrid/onsite             1
remote                           1
remote(Global)/onsite            1
Name: count, dtype: int64
Skill number2 2_skill
Serbia       16
France       10
Poland        7
UK            4
Armenia       2
Cyprus        2
Portugal      1
India         1
Ukraine       1
US            1
Spain         1
Singapore     1
Italy         1
Name: count, dtype: int64
Skill number3 3_skill
fulltime    48
Name: count, dtype: int64
Skill number4 4_skill
senior                       19
middle/senior                 9
middle                        7
senior/lead                   3
lead                          2
head                          2
director                      2
c_level                       1
trainee                       1
junior/middle                 1
junior/middle/senior/lead     1
Name: count, dtype: int64
Skill number5 5_skill
Relocation    48
Name: count, dtype: int64

Я изначально запутался в числе возможных тегов, их оказывается 5, а не 4, поэтому проведя анализ по 5 тегам, видим, что одно из них это relocation, соответственно просто превращаем его в флаг, есть ли relocation или нет. Для всего остального будем исследовать датасет уже с 4 тегами.

In [ ]:
df['relocation'] = df['tags_parsed'].apply(lambda x: 'Relocation' in x)